### ISSUE TITLE
Pod init in xcode 14.1 and mac os ventura 13.0.1

### ISSUE THREAD

**Issue by rupesh0790** [CocoaPods/CocoaPods#11656]
neha@KhiladiAddas-MacBook-Air PlaySlider % pod init

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
    RubyGems : 3.2.32
        Host : macOS 13.0.1 (22A400)
       Xcode : 14.1 (14B47b)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.0.3/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 1d92edb080c40cbd7893f7fcef4c42620ef036ad

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version (56).
/opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:228:in `initialize_from_file'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:113:in `open'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command/init.rb:41:in `validate!'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Unknown+object+version+%2856%29.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - pod init after update it to XCODE 14
   https://github.com/CocoaPods/CocoaPods/issues/11546 [open] [15 comments]
   21 hours ago

 - Error occurred when executing pod init
   https://github.com/CocoaPods/CocoaPods/issues/11536 [open] [16 comments]
   2 days ago

 - RuntimeError - [Xcodeproj] Unknown object version.
   https://github.com/CocoaPods/CocoaPods/issues/10099 [closed] [4 comments]
   28 Sep 2022

and 10 more at:
https://github.com/cocoapods/cocoapods/search?q=%5BXcodeproj%5D%20Unknown%20object%20version%20%2856%29.&type=Issues&utf8=✓
neha@KhiladiAddas-MacBook-Air PlaySlider % 
![Uploading Screenshot 2022-11-16 at 10.35.06 AM.png…]()

**Comment by bhavinchauhanios** [comment]
@rupesh0790 

Found a fix from https://github.com/CocoaPods/CocoaPods/issues/9611#issuecomment-599125090

rm -rf ~/.cocoapods/repos/trunk/ 
pod install

**Comment by oemurlu** [comment]
<img width="263" alt="image" src="https://user-images.githubusercontent.com/102610734/205483386-37b666cb-41cf-40cb-bafe-f4eb73ae9f00.png">
I fixed my error with this method.

**Comment by rupesh0790** [comment]
I've fixed by changed the version 13.0-compatible

**Comment by theogscott** [comment]
Had the same problem, and changed the Xcode Project Format from 14 to 13 when I tried "pod init"

**Comment by TheKamsi** [comment]
> 

how did you get to this

**Comment by rupesh0790** [comment]
![image](https://user-images.githubusercontent.com/94523934/206963778-c74e2281-5be0-4d21-a9dd-4e0b700b5831.png)

**Comment by apple-ihack-geek** [comment]
I ran into this error running pod install from an existing project.  It had a project format of like 6.3.  It still happened when I tried changing it to Xcode 13.0 as well...
I'm using Xcode 14.2 and Ventura 13.0

**Comment by rupesh0790** [comment]
You need to update your system's pod and finish setup

**Comment by apple-ihack-geek** [comment]
> You need to update your system's pod and finish setup

Could you be more specific? I'm already running the latest version of cocoapods.

**Comment by HugeBob** [comment]
> ![image](https://user-images.githubusercontent.com/94523934/206963778-c74e2281-5be0-4d21-a9dd-4e0b700b5831.png)

How do I access this drop down menu? Do I have to create a new project entirely or can I find this somewhere in an already existing project?

**Comment by rupesh0790** [comment]
<img width="1411" alt="Screenshot 2022-12-22 at 10 18 08 AM" src="https://user-images.githubusercontent.com/94523934/209058845-814d2671-6ab9-4eaa-b7cd-aabe2aa66494.png">

**Comment by snes-gsu** [comment]
Fixed by using 
`brew uninstall cocoapods`
`brew install cocoapods`
`pod install`
`pod update`
in this order

**Comment by rupesh0790** [comment]
update your system pod

**Comment by tljstewart** [comment]
> <img alt="image" width="263" src="https://user-images.githubusercontent.com/102610734/205483386-37b666cb-41cf-40cb-bafe-f4eb73ae9f00.png">
> 
> I fixed my error with this method.

Where is this setting?

**Comment by dbk1985** [comment]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin21]
    RubyGems : 3.4.2
        Host : macOS 12.6.1 (21G217)
       Xcode : 14.2 (14C18)
         Git : git version 2.39.0
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile
xxxxxx

### Error

```
JSON::ParserError - unexpected token at '{
  "name": "Realm",
  "version": "10.33.0",
  "cocoapods_version": ">= 1.10",
  "summary": "Realm is a modern data framework & database for iOS, macOS, tvOS & watchOS.",
  "description": "The Realm Database, for Objective-C. (If you want to use Realm from Swift, see the “RealmSwift” pod.)\n\nRealm is a fast, easy-to-use replacement for Core Data & SQLite. Use it with Atlas Device Sync for realtime, automatic data sync. Works on iOS, macOS, tvOS & watchOS. Learn more and get help at https://www.mongodb.com/docs/realm/sdk/swift/.",
  "homepage": "https://realm.io",
  "source": {
    "git": "https://github.com/realm/realm-swift.git",
    "tag": "v10.33.0"
  },
  "authors": {
    "Realm": "realm-help@mongodb.com"
  },
  "libraries": [
    "c++",
    "z",
    "compression"
  ],
  "requires_arc": true,
  "social_media_url": "https://twitter.com/realm",
  "documentation_url": "https://docs.mongodb.com/realm/sdk/swift",
  "license": {
    "type": "Apache 2.0",
    "file": "LICENSE"
  },
  "frameworks": "Security",
  "module_map": "Realm/Realm.modulemap",
  "compiler_flags": "-DREALM_HAVE_CONFIG -DREALM_COCOA_VERSION='@\"10.33.0\"' -D__ASSERTMACROS__ -DREALM_ENABLE_SYNC",
  "prepare_command": "sh scripts/setup-cocoapods.sh",
  "source_files": [
    "include/RLMAccessor.h",
    "include/RLMApp_Private.h",
    "include/RLMArray_Private.h",
    "include/RLMBSON_Private.h",
    "include/RLMCollection_Private.h",
    "include/RLMDictionary_Private.h",
    "include/RLMEvent.h",
    "include/RLMObjectBase_Private.h",
    "include/RLMObjectSchema_Private.h",
    "include/RLMObjectStore.h",
    "include/RLMObject_Private.h",
    "include/RLMOptionalBase.h",
    "include/RLMPropertyBase.h",
    "include/RLMProperty_Private.h",
    "include/RLMProviderClient_Private.h",
    "include/RLMRealmConfiguration_Private.h",
    "include/RLMRealm_Private.h",
    "include/RLMResults_Private.h",
    "include/RLMSchema_Private.h",
    "include/RLMSet_Private.h",
    "include/RLMSwiftProperty.h",
    "include/RLMSyncConfiguration_Private.h",
    "include/RLMSyncSubscription_Private.h",
    "include/RLMSyncUtil_Private.h",
    "include/RLMUpdateResult_Private.h",
    "include/RLMUser_Private.h",
    "Security",
    "Realm/*.{m,mm}"
  ],
  "private_header_files": [
    "include/RLMAccessor.h",
    "include/RLMApp_Private.h",
    "include/RLMArray_Private.h",
    "include/RLMBSON_Private.h",
    "include/RLMCollection_Private.h",
    "include/RLMDictionary_Private.h",
    "include/RLMEvent.h",
    "include/RLMObjectBase_Private.h",
    "include/RLMObjectSchema_Private.h",
    "include/RLMObjectStore.h",
    "include/RLMObject_Private.h",
    "include/RLMOptionalBase.h",
    "include/RLMPropertyBase.h",
    "include/RLMProperty_Private.h",
    "include/RLMProviderClient_Private.h",
    "include/RLMRealmConfiguration_Private.h",
    "include/RLMRealm_Private.h",
    "include/RLMResults_Private.h",
    "include/RLMSchema_Private.h",
    "include/RLMSet_Private.h",
    "include/RLMSwiftProperty.h",
    "include/RLMSyncConfiguration_Private.h",
    "include/RLMSyncSubscription_Private.h",
    "include/RLMSyncUtil_Private.h",
    "include/RLMUpdateResult_Private.h",
    "include/RLMUser_Private.h",
    "Security"
  ],
  "header_mappings_dir": "include",
  "pod_target_xcconfig": {
    "APPLICATION_EXTENSION_API_ONLY": "YES",
    "CLANG_CXX_LANGUAGE_STANDARD": "c++17",
    "CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF": "NO",
    "OTHER_CPLUSPLUSFLAGS": "-isystem \"${PODS_ROOT}/Realm/include/core\" -fvisibility-inlines-hidden",
    "OTHER_CPLUSPLUSFLAGS[arch=armv7]": "-isystem \"${PODS_ROOT}/Realm/include/core\" -fvisibility-inlines-hidden -fno'
/opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:748:in `from_string'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:722:in `from_file'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source.rb:188:in `specification'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:56:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:216:in `search'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=unexpected+token+at+%27%7B%0A++%22name%22%3A+%22Realm%22%2C%0A++%22version%22%3A+%2210.33.0%22%2C%0A++%22cocoapods_version%22%3A+%22%3E%3D+1.10%22%2C%0A++%22summary%22%3A+%22Realm+is+a+modern+data+framework+%26+database+for+iOS%2C+macOS%2C+tvOS+%26+watchOS.%22%2C%0A++%22description%22%3A+%22The+Realm+Database%2C+for+Objective-C.+%28If+you+want+to+use+Realm+from+Swift%2C+see+the+%E2%80%9CRealmSwift%E2%80%9D+pod.%29%5Cn%5CnRealm+is+a+fast%2C+easy-to-use+replacement+for+Core+Data+%26+SQLite.+Use+it+with+Atlas+Device+Sync+for+realtime%2C+automatic+data+sync.+Works+on+iOS%2C+macOS%2C+tvOS+%26+watchOS.+Learn+more+and+get+help+at+https%3A%2F%2Fwww.mongodb.com%2Fdocs%2Frealm%2Fsdk%2Fswift%2F.%22%2C%0A++%22homepage%22%3A+%22https%3A%2F%2Frealm.io%22%2C%0A++%22source%22%3A+%7B%0A++++%22git%22%3A+%22https%3A%2F%2Fgithub.com%2Frealm%2Frealm-swift.git%22%2C%0A++++%22tag%22%3A+%22v10.33.0%22%0A++%7D%2C%0A++%22authors%22%3A+%7B%0A++++%22Realm%22%3A+%22realm-help%40mongodb.com%22%0A++%7D%2C%0A++%22libraries%22%3A+%5B%0A++++%22c%2B%2B%22%2C%0A++++%22z%22%2C%0A++++%22compression%22%0A++%5D%2C%0A++%22requires_arc%22%3A+true%2C%0A++%22social_media_url%22%3A+%22https%3A%2F%2Ftwitter.com%2Frealm%22%2C%0A++%22documentation_url%22%3A+%22https%3A%2F%2Fdocs.mongodb.com%2Frealm%2Fsdk%2Fswift%22%2C%0A++%22license%22%3A+%7B%0A++++%22type%22%3A+%22Apache+2.0%22%2C%0A++++%22file%22%3A+%22LICENSE%22%0A++%7D%2C%0A++%22frameworks%22%3A+%22Security%22%2C%0A++%22module_map%22%3A+%22Realm%2FRealm.modulemap%22%2C%0A++%22compiler_flags%22%3A+%22-DREALM_HAVE_CONFIG+-DREALM_COCOA_VERSION%3D%27%40%5C%2210.33.0%5C%22%27+-D__ASSERTMACROS__+-DREALM_ENABLE_SYNC%22%2C%0A++%22prepare_command%22%3A+%22sh+scripts%2Fsetup-cocoapods.sh%22%2C%0A++%22source_files%22%3A+%5B%0A++++%22include%2FRLMAccessor.h%22%2C%0A++++%22include%2FRLMApp_Private.h%22%2C%0A++++%22include%2FRLMArray_Private.h%22%2C%0A++++%22include%2FRLMBSON_Private.h%22%2C%0A++++%22include%2FRLMCollection_Private.h%22%2C%0A++++%22include%2FRLMDictionary_Private.h%22%2C%0A++++%22include%2FRLMEvent.h%22%2C%0A++++%22include%2FRLMObjectBase_Private.h%22%2C%0A++++%22include%2FRLMObjectSchema_Private.h%22%2C%0A++++%22include%2FRLMObjectStore.h%22%2C%0A++++%22include%2FRLMObject_Private.h%22%2C%0A++++%22include%2FRLMOptionalBase.h%22%2C%0A++++%22include%2FRLMPropertyBase.h%22%2C%0A++++%22include%2FRLMProperty_Private.h%22%2C%0A++++%22include%2FRLMProviderClient_Private.h%22%2C%0A++++%22include%2FRLMRealmConfiguration_Private.h%22%2C%0A++++%22include%2FRLMRealm_Private.h%22%2C%0A++++%22include%2FRLMResults_Private.h%22%2C%0A++++%22include%2FRLMSchema_Private.h%22%2C%0A++++%22include%2FRLMSet_Private.h%22%2C%0A++++%22include%2FRLMSwiftProperty.h%22%2C%0A++++%22include%2FRLMSyncConfiguration_Private.h%22%2C%0A++++%22include%2FRLMSyncSubscription_Private.h%22%2C%0A++++%22include%2FRLMSyncUtil_Private.h%22%2C%0A++++%22include%2FRLMUpdateResult_Private.h%22%2C%0A++++%22include%2FRLMUser_Private.h%22%2C%0A++++%22Security%22%2C%0A++++%22Realm%2F%2A.%7Bm%2Cmm%7D%22%0A++%5D%2C%0A++%22private_header_files%22%3A+%5B%0A++++%22include%2FRLMAccessor.h%22%2C%0A++++%22include%2FRLMApp_Private.h%22%2C%0A++++%22include%2FRLMArray_Private.h%22%2C%0A++++%22include%2FRLMBSON_Private.h%22%2C%0A++++%22include%2FRLMCollection_Private.h%22%2C%0A++++%22include%2FRLMDictionary_Private.h%22%2C%0A++++%22include%2FRLMEvent.h%22%2C%0A++++%22include%2FRLMObjectBase_Private.h%22%2C%0A++++%22include%2FRLMObjectSchema_Private.h%22%2C%0A++++%22include%2FRLMObjectStore.h%22%2C%0A++++%22include%2FRLMObject_Private.h%22%2C%0A++++%22include%2FRLMOptionalBase.h%22%2C%0A++++%22include%2FRLMPropertyBase.h%22%2C%0A++++%22include%2FRLMProperty_Private.h%22%2C%0A++++%22include%2FRLMProviderClient_Private.h%22%2C%0A++++%22include%2FRLMRealmConfiguration_Private.h%22%2C%0A++++%22include%2FRLMRealm_Private.h%22%2C%0A++++%22include%2FRLMResults_Private.h%22%2C%0A++++%22include%2FRLMSchema_Private.h%22%2C%0A++++%22include%2FRLMSet_Private.h%22%2C%0A++++%22include%2FRLMSwiftProperty.h%22%2C%0A++++%22include%2FRLMSyncConfiguration_Private.h%22%2C%0A++++%22include%2FRLMSyncSubscription_Private.h%22%2C%0A++++%22include%2FRLMSyncUtil_Private.h%22%2C%0A++++%22include%2FRLMUpdateResult_Private.h%22%2C%0A++++%22include%2FRLMUser_Private.h%22%2C%0A++++%22Security%22%0A++%5D%2C%0A++%22header_mappings_dir%22%3A+%22include%22%2C%0A++%22pod_target_xcconfig%22%3A+%7B%0A++++%22APPLICATION_EXTENSION_API_ONLY%22%3A+%22YES%22%2C%0A++++%22CLANG_CXX_LANGUAGE_STANDARD%22%3A+%22c%2B%2B17%22%2C%0A++++%22CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF%22%3A+%22NO%22%2C%0A++++%22OTHER_CPLUSPLUSFLAGS%22%3A+%22-isystem+%5C%22%24%7BPODS_ROOT%7D%2FRealm%2Finclude%2Fcore%5C%22+-fvisibility-inlines-hidden%22%2C%0A++++%22OTHER_CPLUSPLUSFLAGS%5Barch%3Darmv7%5D%22%3A+%22-isystem+%5C%22%24%7BPODS_ROOT%7D%2FRealm%2Finclude%2Fcore%5C%22+-fvisibility-inlines-hidden+-fno%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

[!] Automatically assigning platform `iOS` with version `12.0` on target `NiceCut` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by dbk1985** [comment]
> 

这个问题已经解决

'JXPagingView/Paging' cause error

**Comment by ShenYj** [comment]
it has fixed, update Xcodeproj to 1.22.0

**Comment by c1800054work** [comment]
brew uninstall cocoapods
sudo gem install cocoapods
sudo gem update xcodeproj
pod init

This work for me

https://github.com/CocoaPods/CocoaPods/issues/11546#issuecomment-1410663934

**Comment by wsytl** [comment]
update ruby ,update cocoapods,then it works

**Comment by nsuinteger-momatu** [comment]
It gives a hint on what's wrong 

` RuntimeError - [Xcodeproj] Unknown object version (56).`

This is usually xcode version that is incompatible with cocoapods. Simply select xcode 13.0 compatible on your target project and it should work. (The answer was found above, im just clarifying on what it is)

**Comment by ilsalexis** [comment]
I had to also update ruby for this work

**Comment by steady-daddy** [comment]
[This answer](https://stackoverflow.com/a/40324464) from SO helped me fix the error. So it's basically uninstalling a few pod files and then installing the gem. 
I ran into this error probably because I tried installing cocoapods with homebrew and it messed up with one of my ruby versions (2.7, 3.1, 3.2 - RVM).

**Comment by ferhatlageyik** [comment]
gem install --user-install cocoapods
echo 'export PATH="$HOME/.gem/ruby/2.6.0/bin:$PATH"' >> ~/.bashrc
and restart terminal 
source ~/.bashrc
then go to your project directory and write pod init. 
this solution work for me.
