### ISSUE TITLE
RuntimeError - [Xcodeproj] Unknown object version (63).: what is this?

### ISSUE THREAD

**Issue by c00012** [CocoaPods/CocoaPods#12348]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
I tried to run "pod init" to install CoreXLSX library in my new iOS project.

## What did you expect to happen?
I expected to see pod file in my new iOS project.
### Error

```
RuntimeError - [Xcodeproj] Unknown object version (63).
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project.rb:228:in `initialize_from_file'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project.rb:113:in `open'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/init.rb:41:in `validate!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
    RubyGems : 3.5.4
        Host : macOS 14.4.1 (23E224)
       Xcode :  ()
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

**Comment by Brett-Best** [comment]
This is fixed by https://github.com/CocoaPods/Xcodeproj/pull/934.

**Comment by c00012** [comment]
I saw that thread. so, what should I do to fix this?

**Comment by MartinGambit** [comment]
Same problem here trying to update to 15.3 version of Xcode

**Comment by c00012** [comment]
<img width="1134" alt="스크린샷 2024-04-19 오전 6 47 27" src="https://github.com/CocoaPods/CocoaPods/assets/11556229/e3655da9-c3a0-4903-ac91-02b301d9fcc2">
as you can see above picture, when you set project format as "Xcode 15.0" or below(not 15.3), you can avoid the problem.

**Comment by foodbutiksweden** [comment]
Hi guys, unfortunately my mac is not supporting the installing version 15 on xcode. now i have 14 version and error still continues. what can i do?

**Comment by harshal0088** [comment]
> Hi guys, unfortunately my mac is not supporting the installing version 15 on xcode. now i have 14 version and error still continues. what can i do?

Please first update your mac os and you can see option for update xcode in app store.

**Comment by shanth923** [comment]
Hi , I downgraded to Xcode 13 , still I am getting same error !  please check
<img width="548" alt="Screenshot 2024-05-10 at 1 17 51 PM" src="https://github.com/CocoaPods/CocoaPods/assets/56910339/86ebd363-5f85-430b-8506-f6e0476b1b5e">

**Comment by cleberhensel** [comment]
Xcode 15.3 is modifying the project.pbxproj file, updating the objectVersion to 63. This may serve as a temporary alternative or workaround.

<img width="965" alt="image" src="https://github.com/CocoaPods/CocoaPods/assets/746898/95d07dd0-cc4f-4500-a977-217643efe096">

**Comment by lreardon** [comment]
@cleberhensel your solution worked for me. Is this a bug or is this somehow expected behavior?

**Comment by cleberhensel** [comment]
> @cleberhensel your solution worked for me. Is this a bug or is this somehow expected behavior?

I don't know how to respond. Additionally, I also did a build on Azure Pipelines. I expected it to break at pod install, but it built correctly. Maybe there is some configuration in the Azure environment that is not set locally. The Mac model I used on Azure was - https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

**Comment by DikoMahendraa** [comment]
https://github.com/CocoaPods/CocoaPods/issues/12348#issuecomment-2105939759


for temporary solution it's worked for me, thanks.

**Comment by andreyd22** [comment]
> [#12348 (comment)](https://github.com/CocoaPods/CocoaPods/issues/12348#issuecomment-2105939759)
> 
> for temporary solution it's worked for me, thanks.

Thank you!

**Comment by iOSMaster045** [comment]
> <img alt="스크린샷 2024-04-19 오전 6 47 27" width="1134" src="https://private-user-images.githubusercontent.com/11556229/323769698-e3655da9-c3a0-4903-ac91-02b301d9fcc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODkwNjQsIm5iZiI6MTczMjE4ODc2NCwicGF0aCI6Ii8xMTU1NjIyOS8zMjM3Njk2OTgtZTM2NTVkYTktYzNhMC00OTAzLWFjOTEtMDJiMzAxZDlmY2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDExMzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZmE3NjA4OThhMTdiZGQ2YTQ2MzA2ZmQwMTQzZGMwZTg1NjdhYWQxZDJiZGMxNDVjNWE3MTk2MjkyMmY3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rfckKjtXp1a9cA13o1VxlZXVZtKkc-68uNfLaUUmAtA"> as you can see above picture, when you set project format as "Xcode 15.0" or below(not 15.3), you can avoid the problem.

It worked for me too, Thanks a lot :)
