### ISSUE TITLE
ArgumentError - comparison of Fixnum with String failed

### ISSUE THREAD

**Issue by feorlen** [CocoaPods/CocoaPods#3363]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?
pod install before attempting to build a project (Signal-iOS in this case.) I tried it twice with the same result, even after gem update and pod update. 

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.3
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F1066)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.7.11.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6d965046d997b0cb9d67cfe92c26d6dcc213d080
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

link_with ["Signal", "SignalTests"]

pod 'OpenSSL',                    '~> 1.0.201'
pod 'libPhoneNumber-iOS',         '~> 0.8.2'
pod 'AxolotlKit',                 '~> 0.6.2'
pod 'PastelogKit',                '~> 1.2'
pod 'TwistedOakCollapsingFutures','~> 1.0'
pod 'AFNetworking',               '~> 2.5.1'
pod 'Mantle',                     '~> 1.5'
pod 'FFCircularProgressView',     '>= 0.1'
pod 'SCWaveformView',             '~> 1.0'
pod 'YapDatabase/SQLCipher'
pod 'SSKeychain'     
pod 'DJWActionSheet'

pod 'SocketRocket',               :git => 'https://github.com/FredericJacobs/SocketRocket.git', :commit => '73d8a19'
pod 'JSQMessagesViewController',  :git => 'https://github.com/WhisperSystems/JSQMessagesViewController', :commit => '9be8f6ed65eb55368a5ff767f055158cf585065f'
pod 'APDropDownNavToolbar',       :git => 'https://github.com/corbett/APDropDownNavToolbar.git', :branch => 'master'
pod 'UICKeyChainStore',           :podspec => 'Podspecs/UICKeyChainStore.podspec'
```

### Error

```
ArgumentError - comparison of Fixnum with String failed
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:248:in `sort'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:248:in `sorted_array'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:229:in `sorted_array_with_hint'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:140:in `process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:102:in `process_according_to_class'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/yaml_helper.rb:41:in `convert_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.3/lib/cocoapods-core/lockfile.rb:338:in `to_yaml'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/migrator.rb:66:in `block (2 levels) in migrate_to_0_36'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/migrator.rb:66:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/migrator.rb:66:in `block in migrate_to_0_36'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/migrator.rb:53:in `migrate_to_0_36'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/migrator.rb:16:in `migrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:105:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:102:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:89:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Could you possibly share your Podfile.lock?

**Comment by feorlen** [comment]
Here is the contents of that file, for me located in ~/dev/repos/Signal-iOS

PODS:
  - 25519 (1.8)
  - AFNetworking (2.5.1):
    - AFNetworking/NSURLConnection (= 2.5.1)
    - AFNetworking/NSURLSession (= 2.5.1)
    - AFNetworking/Reachability (= 2.5.1)
    - AFNetworking/Security (= 2.5.1)
    - AFNetworking/Serialization (= 2.5.1)
    - AFNetworking/UIKit (= 2.5.1)
  - AFNetworking/NSURLConnection (2.5.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/NSURLSession (2.5.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (2.5.1)
  - AFNetworking/Security (2.5.1)
  - AFNetworking/Serialization (2.5.1)
  - AFNetworking/UIKit (2.5.1):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession
  - APDropDownNavToolbar (1.1)
  - AxolotlKit (0.6.2):
    - 25519 (~> 1.8)
    - HKDFKit (~> 0.0.3)
    - ProtocolBuffers (~> 1.9.7)
  - CocoaLumberjack (1.9.2):
    - CocoaLumberjack/Extensions (= 1.9.2)
  - CocoaLumberjack/Core (1.9.2)
  - CocoaLumberjack/Extensions (1.9.2):
    - CocoaLumberjack/Core
  - DJWActionSheet (1.0.4)
  - FFCircularProgressView (0.5)
  - HKDFKit (0.0.3)
  - JSQMessagesViewController (7.0.0):
    - JSQSystemSoundPlayer (~> 2.0.1)
  - JSQSystemSoundPlayer (2.0.1)
  - libPhoneNumber-iOS (0.8.4)
  - Mantle (1.5.4):
    - Mantle/extobjc (= 1.5.4)
  - Mantle/extobjc (1.5.4)
  - OpenSSL (1.0.201)
  - PastelogKit (1.2):
    - CocoaLumberjack (~> 1.9)
  - ProtocolBuffers (1.9.7)
  - SCWaveformView (1.0.0)
  - SocketRocket (0.3.1-beta2)
  - SQLCipher/common (3.1.0)
  - SQLCipher/fts (3.1.0):
    - SQLCipher/common
  - SSKeychain (1.2.2)
  - TwistedOakCollapsingFutures (1.0.0):
    - UnionFind (~> 1.0)
  - UICKeyChainStore (1.0.7)
  - UnionFind (1.0.1)
  - YapDatabase/common (2.6):
    - CocoaLumberjack (~> 1)
  - YapDatabase/SQLCipher (2.6):
    - SQLCipher/fts
    - YapDatabase/common

DEPENDENCIES:
  - AFNetworking (~> 2.5.1)
  - APDropDownNavToolbar (from `https://github.com/corbett/APDropDownNavToolbar.git`, branch `master`)
  - AxolotlKit (~> 0.6.2)
  - DJWActionSheet
  - FFCircularProgressView (>= 0.1)
  - JSQMessagesViewController (from `https://github.com/WhisperSystems/JSQMessagesViewController`, commit `9be8f6ed65eb55368a5ff767f055158cf585065f`)
  - libPhoneNumber-iOS (~> 0.8.2)
  - Mantle (~> 1.5)
  - OpenSSL (~> 1.0.201)
  - PastelogKit (~> 1.2)
  - SCWaveformView (~> 1.0)
  - SocketRocket (from `https://github.com/FredericJacobs/SocketRocket.git`, commit `73d8a19`)
  - SSKeychain
  - TwistedOakCollapsingFutures (~> 1.0)
  - UICKeyChainStore (from `Podspecs/UICKeyChainStore.podspec`)
  - YapDatabase/SQLCipher

EXTERNAL SOURCES:
  APDropDownNavToolbar:
    :branch: master
    :git: https://github.com/corbett/APDropDownNavToolbar.git
  JSQMessagesViewController:
    :commit: 9be8f6ed65eb55368a5ff767f055158cf585065f
    :git: https://github.com/WhisperSystems/JSQMessagesViewController
  SocketRocket:
    :commit: 73d8a19
    :git: https://github.com/FredericJacobs/SocketRocket.git
  UICKeyChainStore:
    :podspec: Podspecs/UICKeyChainStore.podspec

CHECKOUT OPTIONS:
  APDropDownNavToolbar:
    :commit: 98a606b343c0ccc6cca1cd243b296325716f21e7
    :git: https://github.com/corbett/APDropDownNavToolbar.git
  JSQMessagesViewController:
    :commit: 9be8f6ed65eb55368a5ff767f055158cf585065f
    :git: https://github.com/WhisperSystems/JSQMessagesViewController
  SocketRocket:
    :commit: 73d8a19
    :git: https://github.com/FredericJacobs/SocketRocket.git

SPEC CHECKSUMS:
  25519: 601ffb5d258aa33d642062d6fa4096db210e02e7
  AFNetworking: 8bee59492a6ff15d69130efa4d0dc67e0094a52a
  APDropDownNavToolbar: 62131873890d3a30a2fdc98ffdda180a11e49aa4
  AxolotlKit: c8d6fdd73754aa6432a106ae73f4c24385e253da
  CocoaLumberjack: 205769c032b5fef85b92472046bcc8b7e7c8a817
  DJWActionSheet: d88b302d7c29523e1e9fb9b62cfac46f59bb90d9
  FFCircularProgressView: 723b7a84c412b5d9d2a5531bc716b99965ad7192
  HKDFKit: 5998cf1bbb611e7ecc6bd3eaaef8c7a7da7be949
  JSQMessagesViewController: 5e6beff1d5aeeea71c45cec4057b9c2c22c0aebd
  JSQSystemSoundPlayer: 55528c699a283aae2220d3ae7b8b527d2ecef4b4
  libPhoneNumber-iOS: dbfc7b4128510a4955df3e5a6f125393fc9ebc2f
  Mantle: d5fbaf30fbc58031223af13812c060e15934a1fe
  OpenSSL: 4e990d04b14015c49c800c400b86ae44a4818a5c
  PastelogKit: 8bab71b1d187617a83e7124cffe9eb1a600e6695
  ProtocolBuffers: 37fdd327d36856f965ea9029b5ec0c7120e3a452
  SCWaveformView: 55f0cd6e80df1a46ff70892bc4041f5b7d8ad43c
  SocketRocket: 9cbe08469513356cddc0afcab1ff160bd190296a
  SQLCipher: 981110217eb93c2779c34fb59e646a1c1da918d8
  SSKeychain: cc48bd3ad24fcd9125adb9e0d23dd50b8bbd08b9
  TwistedOakCollapsingFutures: 07aab84fd3958dc94d55ef705b12857d9fbe61d1
  UICKeyChainStore: eef407137f0397e95a3df32cdf05f7e2ddd99647
  UnionFind: 45777a8b6878d3a602af3654cc3a09b87389d356
  YapDatabase: e8da76280ae7f41b24bf0cc7d7e2e7aafac9e473

COCOAPODS: 0.35.0

**Comment by segiddins** [comment]
So, this is actually a bug that's been fixed in 0.36.3, but you'll have to make one little manual tweak for the fix to take effect:

```
s/25519: 601ffb5d258aa33d642062d6fa4096db210e02e7/"25519": 601ffb5d258aa33d642062d6fa4096db210e02e7/
```

**Comment by feorlen** [comment]
That resolved the issue, thanks

**Comment by feorlen** [comment]
Last night making that change to the Podfile.lock allowed me to continue building. Subsequent errors recommended re-installing the Xcode command line tools, which I did, and now I'm back to the same error with CocoaPods. 

Since then I have installed the latest Xcode, re-installed the command line tools, uninstalled and re-installed CocoaPods, updated gems, cloned the project fresh. I've done these things multiple times and still get that same error. I've tried it with and without adding the quotes to Podfile.lock and also changing the CocoaPods version specified in Podfile.lock from 0.35.0 to 0.36.3. Each time removing and re-cloning the project because of invalid lockfile messages.

I've got 0.36.3, which supposedly resolved this issue, and the first time after I added the quotes to Podfile.lock it did. Why would it happen again?

```
   CocoaPods : 0.36.3
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F1066)
       Xcode : 6.2 (6C131e)
         Git : git version 1.7.11.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6d965046d997b0cb9d67cfe92c26d6dcc213d080
```

**Comment by segiddins** [comment]
@feorlen as long as you make that change to the lockfile, and then install again using CocoaPods 0.36.3, I don't see how you could get the same error.

**Comment by feorlen** [comment]
@segiddins my thought as well, of course. I've only used CocoaPods a couple of times and then only because some other thing required it. But I've done everything I can think of short of completely un-installing Xcode and I'm still not getting anywhere. 

Is there some other detail I could provide from my environment? The error information looks identical. This isn't my project I'm trying to build, it's something else that I'd like to potentially work on so of course the first step is to build it. The project's active contributors don't know of any problems because it works fine for them.

**Comment by segiddins** [comment]
Are they also using CocoaPods 0.36.3? Have you tried deleting the Pods folders?

-Samuel E. Giddins

On Apr 4, 2015, at 3:14 PM, feorlen <notifications@github.com> wrote:

@segiddins my thought as well, of course. I've only used CocoaPods a couple of times and then only because some other thing required it. But I've done everything I can think of short of completely un-installing Xcode and I'm still not getting anywhere.

Is there some other detail I could provide from my environment? The error information looks identical. This isn't my project I'm trying to build, it's something else that I'd like to potentially work on so of course the first step is to build it. The project's active contributors don't know of any problems because it works fine for them.

**Comment by feorlen** [comment]
I'm not sure how to tell which version they are using, unless the 

COCOAPODS: 0.35.0

in Podfile.lock indicates that. Must I have the exact one? Their documentation says nothing about installing a particular version. My only communication with them so far was a hasty twitter exchange with one of the developers, so I will need to follow up with (I hope) an email. 

As for the Pods directory, I tried deleting it (starting again with a fresh clone, editing Podfile.lock) and then pod install started downloading things. Part way through I get this error

Fetching podspec for `UICKeyChainStore` from `Podspecs/UICKeyChainStore.podspec`
[!] Unable to find a specification for `OpenSSL (~> 1.0.201)`

Now while that seems problematic enough (is that project relying on a specific version?) it's not the same as CocoaPods throwing an error itself. 

Is that something that would indicate a problem in the project configuration or sources?
