### ISSUE TITLE
Permissions Error While Installing Specific Pod (Google-Mobile-Ads-SDK)

### ISSUE THREAD

**Issue by awojnowski** [CocoaPods/CocoaPods#4045]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

Attempted to build a project with Google-Mobile-Ads-SDK.

* What did you expect to happen?

Installation would occur.

* What happened instead?

Received a permission error.

* Remarks

I believe this is some sort of issue with the specific pod. This behaviour is not exhibited elsewhere, with other pods. Haven't been able to find anything online about it though so it may be an issue with my installation.

**Update**: For some reason it appears as if this specific pod is trying to install based on the root directory `/` as opposed to my user's home directory `/users/aaron/`. Not sure why. If I create the directory `/Aaron/` with the correct permissions it creates the pod's directory in there versus going through `users/aaron/....`..

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d2c8781737dacd8fb8fa51951262846288e2fe23
               **redacted**
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '8.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

pod 'Google-Mobile-Ads-SDK'
```

### Error

```
Errno::EACCES - Permission denied @ dir_s_mkdir - /Aaron
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `each'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/pathname.rb:564:in `mkpath'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/headers_store.rb:100:in `add_file'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/headers_store.rb:75:in `block in add_files'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/headers_store.rb:74:in `map'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/headers_store.rb:74:in `add_files'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:141:in `block (4 levels) in link_headers'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:140:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:140:in `block (3 levels) in link_headers'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `block (2 levels) in link_headers'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `block in link_headers'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:115:in `link_headers'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:41:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:562:in `install_file_references'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

Here is the output for my project directory:

```
aaron:~/Desktop/test$ ls -la .
total 8
drwxr-xr-x   9 aaron  staff  306 19 Aug 19:23 .
drwx------+  5 aaron  staff  170 19 Aug 19:22 ..
drwxr-xr-x   4 aaron  staff  136 19 Aug 19:22 Build
drwxr-xr-x   4 aaron  staff  136 19 Aug 19:22 DerivedData
-rw-r--r--   1 aaron  staff  120 19 Aug 19:23 Podfile
drwxrwxrwx   6 aaron  staff  204 19 Aug 19:23 Pods
drwxr-xr-x  10 aaron  staff  340 19 Aug 19:22 test
drwxr-xr-x   5 aaron  staff  170 19 Aug 19:22 test.xcodeproj
drwxr-xr-x   4 aaron  staff  136 19 Aug 19:22 testTests
```

Here is the `/usr/` directory:

```
aaron:/usr$ ls -la .
total 8
drwxr-xr-x@   12 root   wheel    408 16 Oct  2014 .
drwxr-xr-x    35 root   wheel   1258 17 Aug 16:40 ..
drwxr-xr-x     5 root   wheel    170  9 Sep  2014 X11
lrwxr-xr-x     1 root   wheel      3 16 Oct  2014 X11R6 -> X11
drwxr-xr-x  1053 root   wheel  35802 30 Jun 13:44 bin
drwxr-xr-x   257 root   wheel   8738 30 Jun 13:44 include
drwxr-xr-x   272 root   wheel   9248 30 Jun 13:44 lib
drwxr-xr-x   170 root   wheel   5780 30 Jun 13:47 libexec
drwxrwxr-x    19 aaron  staff    646 30 Jul 22:44 local
drwxr-xr-x   245 root   wheel   8330 30 Jun 13:44 sbin
drwxr-xr-x    46 root   wheel   1564 16 Oct  2014 share
drwxr-xr-x     4 root   wheel    136 16 Oct  2014 standalone
```

**Comment by segiddins** [comment]
This is now fixed on `master`.

**Comment by felipesabino** [comment]
@segiddins 

> This is now fixed on master.

Is there a specific commit/PR related to this fix? 

We are experiencing the same error on version `0.39.0.rc.1`, which is only 2 commits behind today's `master`...

**Comment by segiddins** [comment]
You'll need to remove the pods directory, but broken sandboxes will no longer be created.

**Comment by maxbrunner** [comment]
@segiddins working here with @felipesabino 

We removed the repository pods directory and also `~/Library/Caches/CocoaPods/` and `~/.cocoapods/repos/master/` but the problem remains.

Here is the full verbose log: https://gist.github.com/maxbrunner/4f581a5a74e3ad8c8d01

**Comment by segiddins** [comment]
Ah sorry, it's a different bug than I thought.

**Comment by iwasrobbed** [comment]
Also getting this when installing `NewRelicAgent` on the 1.0.0 beta and it seems to be trying to mkdir for the wrong path within `Users/Valet` that doesn't even exist versus the original path `Users/rob` that it was run from. `Valet` is actually the target's name in this case

```
Errno::EACCES - Permission denied @ dir_s_mkdir - /Users/Valet
/Users/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
/Users/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
/Users/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
/Users/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
/Users/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
/Users/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:210:in `each'
/Users/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
/Users/rob/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/pathname.rb:564:in `mkpath'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/sandbox/headers_store.rb:99:in `add_file'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/sandbox/headers_store.rb:75:in `block in add_files'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/sandbox/headers_store.rb:74:in `map'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/sandbox/headers_store.rb:74:in `add_files'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:139:in `block (4 levels) in link_headers'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:138:in `each'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:138:in `block (3 levels) in link_headers'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:117:in `each'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:117:in `block (2 levels) in link_headers'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:116:in `each'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:116:in `block in link_headers'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:144:in `message'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:115:in `link_headers'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:41:in `install!'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:621:in `install_file_references'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:165:in `block in generate_pods_project'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:163:in `generate_pods_project'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:115:in `install!'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/project.rb:97:in `run'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command.rb:48:in `run'
/Users/rob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0.beta.1/bin/pod:44:in `<top (required)>'
/Users/rob/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/rob/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>’
```

**Comment by segiddins** [comment]
@iwasrobbed I can't reproduce this... can you share the output of `pod env`?

**Comment by iwasrobbed** [comment]
@segiddins For sure, see below (I removed all other pods and still repros using only the `NewRelicAgent` pod by itself)

### Stack

```
   CocoaPods : 1.0.0.beta.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.5 (14F1505)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/rob/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f7ba2af38a58bef62a556e3c8d1c93ff88440ef7
```

### Installation Source

```
Executable Path: /Users/rob/.rvm/gems/ruby-2.2.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.1
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.1
```

### Podfile

```ruby
platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# use frameworks for Swift
use_frameworks!

target 'Valet' do
  
  # New Relic
  pod 'NewRelicAgent'
  
end
```

**Comment by segiddins** [comment]
I'm sorry, I just cannot reproduce this...

**Comment by iwasrobbed** [comment]
@segiddins Seems to be a localized issue on my machine / dir structure; I'll update here if I figure out what the issue actually is

**Comment by iwasrobbed** [comment]
Not sure what the deal was. Uninstalled all the various `cocoapods` gem versions and variations, reinstalled just the version I wanted and that didn't do anything. I then did a fresh clone of the project and installed the pods in a new terminal window and it seemed to clear up @segiddins

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by ZW19920614** [comment]
### Error
    
    ```
    Errno::EACCES - Permission denied @ dir_s_mkdir - /Desktop
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir'
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `fu_mkdir'
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `reverse_each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `block in mkdir_p'
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:576:in `mkpath'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:120:in `add_file'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:100:in `block in add_files'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:99:in `map'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:99:in `add_files'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:164:in `block (4 levels) in link_headers'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:162:in `each'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:162:in `block (3 levels) in link_headers'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:146:in `each'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:146:in `block (2 levels) in link_headers'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:135:in `each'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:135:in `block in link_headers'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:134:in `link_headers'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:44:in `install!'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `install_file_references'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:183:in `generate_pods_project'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:119:in `install!'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/bin/pod:23:in `load'
    /Users/zhangwei/.rvm/gems/ruby-2.5.1/bin/pod:23:in `<main>'
    ```
    
    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    
    [!] Oh no, an error occurred.
    
    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FDesktop&type=Issues
    
    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new
    
    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
    
    Don't forget to anonymize any private data!
    
    Looking for related issues on cocoapods/cocoapods...
     - You cannot run CocoaPods as root
       https://github.com/CocoaPods/CocoaPods/issues/6795 [closed] [2 comments]
       31 Jul 2018
    
     - Permissions Error While Installing Specific Pod (Google-Mobile-Ads-SDK)
       https://github.com/CocoaPods/CocoaPods/issues/4045 [closed] [11 comments]
       30 Apr 2016
    
Error output from CocoaPods:
↳
    
    [!] Automatically assigning platform `ios` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
    
    [!] A license was specified in podspec `fluttertoast` but the file does not exist - /Users/zhangwei/Desktop/client-flutter/ios/.symlinks/plugins/fluttertoast/LICENSE
Error running pod install
pengzhilongdeMac-mini:client-flutter zhangwei$ pod env

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8fa0eaf996c9c6534e6b3ce273ad3e313aeb9277
```

### Installation Source

```
Executable Path: /Users/zhangwei/.rvm/gems/ruby-2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     :     @@@@1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
