### ISSUE TITLE
Undefined symbols for architecture arm64 for Cocoapod

### ISSUE THREAD

**Issue by mohitsharma0690** [CocoaPods/CocoaPods#4076]
Hi, I'm trying to use GoogleCloudMessaging pod in my project but I seem to be getting linker errors whenever I try to build it. 
```
"_OBJC_CLASS_$_GSDK_GTMLogMininumLevelFilter", referenced from:
      objc-class-ref in libGGLInstanceIDLib.a(GGLInstanceID.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm using CocaaPods 0.38.2.
Deployment Target: iOS 8.3
 
```
   source 'https://github.com/CocoaPods/Specs.git'

   pod 'GGLInstanceID'
   pod 'GoogleCloudMessaging'
```

I looked at the library and it is indeed built for arm64. I'm not sure if this is an issue with the pod itself or not?

Any help would be appreciated.

**Comment by neonichu** [comment]
I believe this might have been fixed by #3832

**Comment by mohitsharma0690** [comment]
Can't test it with 0.39.beta2 because of #4085

**Comment by segiddins** [comment]
Can you try with Beta 3? Thanks!

**Comment by mohitsharma0690** [comment]
I still see the same issue. 

Here is what the library outputted for me `Architectures in the fat file: libGGLInstanceIDLib.a are: armv7 i386 x86_64 arm64`

**Comment by kylef** [comment]
The problem seems to come from the pod `GGLInstanceID` (a dependency of `GoogleCloudMessaging `). This pod depends on `GoogleSymbolUtilities` which has the description:

> Shared Google library for renamed symbols to avoid duplicate symbol errors. Not intended for direct use.

I have absolutely no idea how how this works, but perhaps it's renaming some symbol here incorrectly?

**Comment by mohitsharma0690** [comment]
Both of the libs seem to be having the same issue. It definitely doesn't seem like a CocoaPods issue. I'll close this one.
