### ISSUE TITLE
Unable to satisfy the following requirements with Podfile, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by bf3400** [CocoaPods/CocoaPods#4373]
bogon:sgarss yunji$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `AFNetworking` required by `Podfile`
- `AFNetworking (= 2.6.0)` required by `Podfile.lock`

Specs satisfying the `AFNetworking` dependency were found, but they required a higher minimum deployment target.

Specs satisfying the `AFNetworking (= 2.6.0)` dependency were found, but they re

**Comment by segiddins** [comment]
Try running `pod update AFNetworking`.

**Comment by orta** [comment]
Sounds like you want to use a higher deployment target.

**Comment by timbrom** [comment]
I have what I think is a similar issue. I'm trying to install the JBWebViewController cocoapod using cocoapod 0.39.0 and getting the following error message:

$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

ARChromeActivity (= 1.0) required by JBWebViewController (1.0.3)
JBWebViewController required by Podfile
Specs satisfying the JBWebViewController dependency were found, but they required a higher minimum deployment target.`

0.38.2 successfully resolves the dependency on ARChromeActivity and installation succeeds.

I tried increasing the deployment target to see if that fixed the problem. 7.0 gave the above error message, I tried increasing to 8.0 and got this error message:

[!] Unable to satisfy the following requirements:

- `ARChromeActivity (= 1.0)` required by `JBWebViewController (1.0)`

I'm brand-new to cocoapods and IOS development, so I'm not sure what other information would be useful. Let me know if any more information is required.

**Comment by alexmcarthur** [comment]
I ran into a similar issue, where the deployment target in my Podfile was '7' (which should satisfy AFNetworking). I had to change this to '7.0' to get it to work.

```
platform :ios, '7'
```
->
```
platform :ios, '7.0'
```
AFNetworking needs '7.0'
```
$ pod spec cat AFNetworking | grep -A 2 platform
  "platforms": {
    "ios": "7.0",
    "osx": "10.9",
--
      "platforms": {
        "ios": "7.0",
        "osx": "10.9"
--
      "platforms": {
        "ios": "7.0",
        "osx": "10.9"
--
      "platforms": {
        "ios": "7.0",
        "osx": "10.9",
--
      "platforms": {
        "ios": null
      },
```

**Comment by yao23** [comment]
I tried 
        pod 'AFNetworking', '2.6.1'
and
       pod update 

Xcode 7 and target 7.0

**Comment by segiddins** [comment]
This is probably fixed by https://github.com/CocoaPods/Core/pull/275, but I'd need a podfile that reproduces the issue to be sure.

**Comment by segiddins** [comment]
Closing as fixed by https://github.com/CocoaPods/Core/pull/275, since we never got a podfile.

**Comment by timbrom** [comment]
Sorry about that, my notifications were going to an email account I don't use very often. Here's a minimal podfile that exhibits the issue.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'JBWebViewController'
```

**Comment by segiddins** [comment]
Thanks, confirmed as fixed!

**Comment by scotteg** [comment]
Got this error in an older project that did not have CocoaPods installed yet. I had just updated it and cleared out the deployment target (i.e., default to latest). When I added CocoaPods and attempted to add a pod (ChameleonFramework), I got the error. However, if I explicitly set the deployment target (e.g., to 9.1), I was able to add that pod.

In a new project that I just created, I was able to integrate CocoaPods and add the same pod, with the deployment target left blank.

Here's the older project if you want to test it out (CocoaPods is not added): https://github.com/scotteg/LayerPlayer

**Comment by segiddins** [comment]
@scotteg this should be fixed on master now

**Comment by scottyseus** [comment]
I am getting this error with iOS KML Framework pod:
```
pod update GoogleMaps
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `iOS-GPX-Framework (~> 0.0)` required by `Podfile`

Specs satisfying the `iOS-GPX-Framework (~> 0.0)` dependency were found, but they required a higher minimum deployment target.
```

The problem was that I had the platform specifying line (e.g. `platform :ios, '5.1'`) twice in the podfile. Removing the second line resolved the issue. I am just leaving this comment here in case anyone else runs into the same problem.

**Comment by wkoszek** [comment]
@segiddins I just upgraded to pod `0.39.0`. I'm hitting this issue too. Had to go from:

```
s.platform = :ios, "7.0"
```

to `6.0`. With `7.0` I was getting the same problem as other guys. To reproduce:

```
git clone https://github.com/twinprime/TwinPrimeSDK-example-good
cd TwinPrimeSDK-example-good/SampleApp
cat > Podfile
pod "TwinPrimeSDK", :podspec => './TwinPrimeSDK.podspec'
```

CTRL+D. Then another file:

```
cat > TwinPrimeSDK.podspec
Pod::Spec.new do |s|
  s.name         = "TwinPrimeSDK"
  s.version      = "1.23.0.3"
  s.summary      = "Twin Prime SDK"
  s.description  = "Twin Prime iOS SDK"
  s.license      = { :type => "Copyright by Twin Prime Inc",
                     :text => "Copyright by Twin Prime Inc" }
  s.homepage     = "http://twinprime.com"
  s.author       = { "Twin Prime Support" => "support@twinprime.com" }

  s.source       = { :git => "https://github.com/twinprime/tp-sdk.git", :tag => s.version }
  s.platform     = :ios, "7.0"

  s.source_files = "**/*.h"
  s.vendored_library = "TwinPrimeSDK/libtwinprime.a"

  s.frameworks = "CFNetwork", "SystemConfiguration", "MobileCoreServices", "CoreTelephony", "CFNetwork"
  s.libraries = "z"
end
```

CTRL+D.

`pod install` gives me:

```
pod install
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `TwinPrimeSDK` from `./TwinPrimeSDK.podspec`
[!] Unable to satisfy the following requirements:

- `TwinPrimeSDK (from `./TwinPrimeSDK.podspec`)` required by `Podfile`

Specs satisfying the `TwinPrimeSDK (from `./TwinPrimeSDK.podspec`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by segiddins** [comment]
@wkoszek but I believe it's fixed on master?

**Comment by wkoszek** [comment]
@segiddins if `0.39.0` isn't yet master, I'll just wait and ping you, if it happens again.

**Comment by segiddins** [comment]
0.39 was released before I fixed the bug

**Comment by SmallElephant** [comment]
- `AFNetworking (~> 3.0.0-beta.0)` required by `Podfile`,when I use
`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'`
I have try many ways:
 1.pod search AFNetworking，I found  AFNetWoring version is 2.6.
 2.pod --version,0.39.0
 3.xCode version,7.2
 4.deplyment target,8.0
can you give me some introduction?

**Comment by segiddins** [comment]
@SmallElephant try with 1.0?

**Comment by diakonos** [comment]
Encountering a similar issue as well trying to update FBSDK pods.

```
[!] Unable to satisfy the following requirements:

- `Bolts (~> 1.5)` required by `FBSDKCoreKit (4.9.0)`

Specs satisfying the `Bolts (~> 1.5)` dependency were found, but they required a higher minimum deployment target.
```

Previously `FBSDKCoreKit` was set to `4.2.0` and `FBSDKLoginKit` was set to `4.1.0`.

As far as I can tell, `Bolts` requires a minimum iOS version of 6.0...

I've tried running `pod install` on the command line and also using the CocoaPods app. I've also tried increasing my podfile's minimum deployment target to 9.0. Nothing's worked.

Previously I was on CocoaPods 0.39.0, and after reading this thread I updated to 1.0.0.beta.3, but there was no difference. Here's some info on my current CocoaPods installation and Podfile:

> ### Stack
> 
> ```
>    CocoaPods : 1.0.0.beta.3
>         Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
>     RubyGems : 2.5.0
>         Host : Mac OS X 10.11.3 (15D21)
>        Xcode : 7.2 (7C68)
>          Git : git version 2.6.2
> Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
> Repositories : master - https://github.com/CocoaPods/Specs.git @ 3faec6af3ea4de497518b749b93c6b18063cad43
> ```
> 
> ### Installation Source
> 
> ```
> Executable Path: /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod
> ```
> 
> ### Plugins
> 
> ```
> cocoapods-deintegrate     : 1.0.0.beta.1
> cocoapods-plugins         : 1.0.0.beta.1
> cocoapods-plugins-install : 0.0.1
> cocoapods-search          : 1.0.0.beta.1
> cocoapods-stats           : 1.0.0.beta.3
> cocoapods-trunk           : 1.0.0.beta.2
> cocoapods-try             : 1.0.0.beta.2
> ```
> 
> ### Podfile
> 
> ```ruby
> platform :ios, '8.0'
> use_frameworks!
> 
> def core_pods
> 	pod 'Alamofire', '~> 3.1'
> 	pod 'AlamofireImage', '~> 2.1'
> 	pod 'AlamofireObjectMapper', '~> 2.1'
> 	pod 'Charts', '~> 2.1'	
> 	pod 'Crashlytics', '~> 3.6'
> 	pod 'DKVerticalColorPicker', '~> 1.0'
> 	pod 'EAIntroView', '~> 2.8.1'
> 	pod 'EDStarRating', '~> 1.1'
> 	pod 'Fabric', '~> 1.6.4'
> 	pod 'Google/Analytics'
> 	pod 'JSQMessagesViewController', '~> 7.2'
> 	pod 'Kingfisher', '~> 1.6'
> 	pod 'Mixpanel', '~> 2.8'
> 	pod 'Optimizely-iOS-SDK', '~> 1.3'
> 	pod 'Parse', '~> 1.9'
> 	pod 'PubNub', '~> 4.1'
> 	pod 'ReachabilitySwift', '~> 2.1'
> 	pod 'SDCAlertView', '~> 3.0'
> 	pod 'SwiftDate', '~> 3.0'
> 	pod 'SZTextView', '~> 1.2'
> 	pod 'TCCopyableLabel', '~> 1.0.1'
> 	pod 'Whisper', '~> 2.0'
> end
> 
> def fb_pods
> 	pod 'FBSDKCoreKit', '~> 4.9'
> 	pod 'FBSDKLoginKit', '~> 4.9'
> end
> 
> def cn_pods
> 	pod 'ShareSDK3'
> 	pod 'MOBFoundation'
> 	pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
> 	pod 'ShareSDK3/ShareSDKUI'
> end
> 
> target 'Target 1' do
> 	core_pods
> 	fb_pods
> 	cn_pods
> end
> 
> target 'Target 2' do
> 	core_pods
> 	fb_pods
> 	cn_pods
> end
> 
> target 'Target 3' do
> 	core_pods
> 	fb_pods
> 	cn_pods
> end
> 
> target 'Target 4' do
> 	core_pods
> 	fb_pods
> 	cn_pods
> end
> 
> target 'Target 5' do
> 	core_pods
> 	fb_pods
> 	cn_pods
> end
> ```

**Comment by rlam3** [comment]
I'm getting the same error with 1.0 cocoapods.

**Comment by segiddins** [comment]
@rlam3 did you run `pod repo update` as the error message suggests?

**Comment by Savankumar-vaishnav** [comment]
Unable to update. 


[!] Unable to satisfy the following requirements:

- `AFNetworking` required by `Podfile`
- `AFNetworking` required by `Podfile`
- `AFNetworking` required by `Podfile`
- `AFNetworking (>= 2.0.0)` required by `IOSLinkedInAPI (2.0.0)`
- `AFNetworking (~> 3.0)` required by `InstagramKit (3.8)`
- `AFNetworking (~> 3.0)` required by `InstagramKit/Exclude-UICKeyChainStore (3.8)`

Specs satisfying the `AFNetworking, AFNetworking (>= 2.0.0), AFNetworking (~> 3.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by Savankumar-vaishnav** [comment]
I have already set minimum target is  iOS 9

**Comment by jonasman** [comment]
are you sure this is fixed?
I get this problem when using cocoapods 1.0 on travis ci:

> [!] Unable to satisfy the following requirements:
- `PromiseKit/CorePromise (~> 3.2.0)` required by `Podfile`
- `PromiseKit/CorePromise (~> 3.2.0)` required by `Podfile`
- `PromiseKit/CorePromise (~> 3.2.0)` required by `Podfile`
- `PromiseKit/CorePromise (= 3.2.0)` required by `Podfile.lock`
None of your spec sources contain a spec satisfying the dependencies: `PromiseKit/CorePromise (~> 3.2.0), PromiseKit/CorePromise (= 3.2.0)`.


from https://travis-ci.org/jonasman/TeslaSwift

podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

pod 'PromiseKit/CorePromise' , '~> 3.2.0'
pod 'ObjectMapper'

target 'TeslaSwift' do
end

target 'TeslaSwiftTests' do
	pod 'Mockingjay' , :git => 'https://github.com/kylef/Mockingjay.git' , :branch => 'master'
end
````

**Comment by jonasman** [comment]
adding `- pod repo update` to travis.yml fixes the issue :)

**Comment by sagarindurkar** [comment]
Hello @segiddins i do get the same error while adding twillio pod 
source 'https://github.com/twilio/cocoapod-specs'
target :MyProject do
    pod 'TwilioConversationsClient', '~>0.25.0'
end

it show error as,

Mangos-MacBook-Pro:pulse UserRoot $ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `ARChromeActivity (= 1.0.0)`

suggest what's going wrong?

**Comment by ThanhTuNguyen** [comment]
its 2017 and i still got same problem, its simple cannot update 

> pod update AFNetworking
> ....
> Using AFNetworking (2.4.1)
> ....
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There are 9 dependencies from the Podfile and 15 total pods installed.

if i try to add line in pod file and pod install or update

> pod 'AFNetworking', '~> 3.0'

the result will be some kind similar 

> - `AFNetworking (= 3.0)` required by `Podfile.lock`
> - `AFNetworking (= 2.4.1)` required by `DZNPhotoPickerController/Services (1.6.1)`

even when i force to change 2.4.1 into 3.0 in podflie.clock,  its still the same 

PS:  I already "pod repo update"

**Comment by benasher44** [comment]
@ThanhTuNguyen that version of DZNPhotoPickerController/Services has a requirement for version 2 of AFNetworking, which isn't compatible with version 3. This is why CocoaPods isn't allowing the update. It appears that DZNPhotoPickerController has posted an updated (version 2) that does support AFNetworking 3. I suggest that you update your DZNPhotoPickerController pod as well. Hope that helps!

**Comment by i-sachin** [comment]
Facing the same issue in my project.
If not solution, do we have any workaround for this issue?

**Comment by Victory886** [comment]
platform : ios , 修改成功  '8.0 就可以用了。

**Comment by CaiWanFeng** [comment]
Change the platform in your podfile.

**Comment by nab0y4enko** [comment]
I have a suspicion that `~> 2.3.1` fits maximum for `2.3.9` , but not for `2.4.0`.

**Comment by LetsNurtureGit** [comment]
Provide a global platform for iOS at the top of the pod file.

**platform :ios, '9.0'**

**Comment by westeast** [comment]
i fix this problem by update "platforms": {
    "ios": "7.0"," to "10.0"  for another pod package

**Comment by akjesto** [comment]
I have got the issue like the following

![Screen Shot 2020-05-08 at 8 49 36 AM](https://user-images.githubusercontent.com/8862491/81366691-e8d10600-9108-11ea-934c-9b77982fc5e0.png)

In my pod file like the following
```
platform :ios, '10.0'
pod 'AFNetworking','~> 4.0.1'
pod 'AFOAuth2Manager','~> 3.0'
```

**Comment by rajlakshmi12** [comment]
@akjesto Hey, did you find any solution for it? I am facing the same problem. and not getting any way-out. Please help.

**Comment by akjesto** [comment]
@rajlakshmi12 
Update your Podfile like this:
```
pod 'AFNetworking', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
pod 'AFOAuth2Manager','~> 3.0'
```
Please check the following link
https://github.com/AFNetworking/AFNetworking/issues/4567

**Comment by DeviOSSushant01** [comment]
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AgoraUIKit_iOS":
  In Podfile:
    AgoraUIKit_iOS (~> 1.0)

Specs satisfying the `AgoraUIKit_iOS (~> 1.0)` dependency were found, but they required a higher minimum deployment target.

Solution AnyOne
