### ISSUE TITLE
`xcodeproj 'MyProject', 'QA' => :debug` does not work as expected

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#4852]
I would like to DEBUG all pods for my target `'My-Debug'`, no matter the configuration. So I wrote my Podfile as this:

    source 'https://github.com/CocoaPods/Specs.git'
    source 'ssh://git@example.com:7999/private.git'
    
    def default_pods
        # private pod
        pod 'Blurbs', '~> 0.1'
        # public pod
        pod 'Mixpanel', '~> 2.9'
    end
    
    def calabash_pods
        #public pod
        pod 'Calabash', '~> 0.17'
    end
    
    target 'My-Release' do
        xcodeproj 'MyProject', 'Live' => :release, 'Dev' => :release, 'QA' => :release
        default_pods
    end
    
    target 'My-Debug' do
        xcodeproj 'MyProject', 'Live' => :debug, 'Dev' => :debug, 'QA' => :debug
        default_pods
    end
    
    target 'My-Calabash' do
        xcodeproj 'MyProject', 'Live' => :release, 'Dev' => :release, 'QA' => :release
        default_pods
        calabash_pods
    end

I tried Cocoapods 0.39.0 and 1.0.0 beta 2. But both have the same issue: target `'My-Debug'` will not be configured for `:debug` configuration for pods.

**Comment by neonichu** [comment]
I'm not quite sure how `xcodeproj` works when it is specified per target, but you'll definitely have to turn off target deduplication for this to even be meaningful. There will be only one target per Pod and therefore also only one build configuration.

**Comment by Coeur** [comment]
Thank you neonichu. But that did not solve it.
* I added on top `install! 'cocoapods', :deduplicate_targets => false`
* I changed `xcodeproj` to `project`
* I used cocoapods 1.0.0beta3

**Comment by segiddins** [comment]
This should be fixed in beta 4

**Comment by Coeur** [comment]
@neonichu, @segiddins, @mrackwitz, thanks. So happy, that I made a quick presentation on that yesterday: http://fr.slideshare.net/AntoineCur/cocoa-tip-for-cocoaheads-shanghai-february-2016

**Comment by Coeur** [comment]
But when using deduplication, I get:

    [!] [Xcodeproj] Generated duplicate UUIDs:

**Comment by mrackwitz** [comment]
As a workaround you can disable the custom deterministic UUID generation algorithm by putting the following in your Podfile:
```ruby
install! 'cocoapods',
         :deterministic_uuids => false,
```

**Comment by Coeur** [comment]
By the way, `project 'MyProject', 'QA' => :debug` still doesn't work as expected, so I will provide you a sample workspace soon.

**Comment by segiddins** [comment]
@Coeur you can't have a mix of debug and release for the same configuration. We should error when that happens though

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by krystiansliwa** [comment]
Hi, I monitor this issue because I have similar problem with cocoapods integration:
http://stackoverflow.com/questions/35228368/xcode-linking-framework-doesnt-work-when-use-custom-build-configuration
I have checked this with new rc1 version but problem still exists

**Comment by Coeur** [comment]
@krystiansliwa, I gave up on this matter after reading "_you can't have a mix of debug and release for the same configuration_" from Samuel. And your Podfile is using the same configuration ('Development' or 'Production') for two targets (PrivateFramework and MainProject). So the implicit rules for PrivateFramework may be conflicting with the explicit rules of MainProject.

**Comment by krystiansliwa** [comment]
@Coeur Thanks 👍I didn't catch that when reading unfortunately
Solution for that is to create new targets each for configuration (Production, Development) ?
