### ISSUE TITLE
Signing for requires a development team. Select a development team in the Target Editor. in Xcode 8 and Swift 3.  🌈

### ISSUE THREAD

**Issue by pjtnt11** [CocoaPods/CocoaPods#5531]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

I upgraded my swift files to swift 3 using Xcode.

## What did you expect to happen?

My app should have upgraded to swift 3 with no problem but...

## What happened instead?

Instead I got this error from the cocoa pods framework:

`Signing for --- requires a development team. Select a development team in the Target Editor.
`
I also got another error probably having to do with this same issue

`Code signing is required for product type 'Framework' in SDK 'iOS 10.0'`

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G12a)
       Xcode : 8.0 (8S128d)
         Git : git version 2.8.1 (Apple Git-69)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 56702ce01de6d6996b4dfe39c0255ce7b08752bd
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by basvankuijck** [comment]
I know it's a bit self explanatory, but to make the project actually build again, select a `Development team` under the `General` tab per individual Pod target.

Every time you run `pod install` or `pod update` you have to repeat those steps.

I know it isn't that much of a future-proof solution, but you're able to build your project (for now)

**Comment by pjtnt11** [comment]
@basvankuijck Thank you, my issue is fixed now

**Comment by davetroy** [comment]
This is very annoying if you have more than a few pods; every time one runs `pod install` each pod must have a team assigned. It would be awesome if there was a way to do this automatically with a `post_install` hook. Is there?

**Comment by dral3x** [comment]
I think this is a real issue and should not be closed.
The proposed "solution" is just a workaround and not a proper solution.

Is there any other Github issue that is taking care of this?
Thanks

**Comment by dral3x** [comment]
A better workaround is to run this in the `post_install`

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Signing
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = config.name.include?('Debug') ? '<DEVERLOPER ID>/' : '<TEAM ID>/'
        end
    end
end
```

**Comment by orta** [comment]
This should be fixed in the 1.1 beta, have you given it a try?

**Comment by dral3x** [comment]
You're right @orta ! With 1.1.0 beta 1 this is not needed anymore. 👍

**Comment by dimohamdy** [comment]
@dral3x what's value of "DEVERLOPER ID" is it developer email ?

**Comment by dral3x** [comment]
@dimohamdy no, it's the number that identify your account.
You can see them inside your keychain. 

The DEVERLOPER ID is the one that identify your development certificate
`iPhone Developer: email (DEVELOPER ID)`

The TEAM ID is the one that identify your distribution certificate 
`iPhone Distribution: company name (TEAM ID)`

**Comment by williamsjj** [comment]
Use 1.1.0.rc.2, the code signing settings on my Pod targets still have Automatic Code Signing unchecked. Is that expected? I was thinking it would match my main app target which has Automatic Code Signing enabled and my team chosen.

**Comment by wkoszek** [comment]
I'm hitting the same issue. As suggested I've upgraded to:

```
$ pod --version
1.1.0.rc.2
```

But I'm still hitting this:

```
Signing for "SampleApp" requires a development team. Select a development team in the project editor.
```

**Comment by engmsaleh** [comment]
@dral3x Your workaround didn't work with me :(

**Comment by dral3x** [comment]
@engmsaleh I'm not using that workaround since I updated cocoapods to version 1.1.0.beta.1

**Comment by engmsaleh** [comment]
@dral3x Thanks I have installed the beta version as suggested and solved the problem :).

**Comment by traviskaenel** [comment]
@dral3x Sorry, I'm new to this. I tried updating cocoapods but it didn't work. I honestly don't even know what that it. I tried copy/pasting the Install: on the rubygems.org website into Terminal, but got this error: 
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
