### ISSUE TITLE
Throw an informative exception when using git < 1.8.5

### ISSUE THREAD

**Issue by jingidy** [CocoaPods/CocoaPods#6078]
### Command

```
/usr/local/bin/pod install
```
### Report
- What did you do?

`pod install`
- What did you expect to happen?

Re-install all cocoapods so they work with cocoapods 1.1.1 and xcode 8
- What happened instead?

The first error I got was `[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.`

I've tried using `pod repo add` but it just told me to do `pod init` which I can't do since I already have a Podfile. I tried uninstalling and reinstalling the cocoapods gem but it didn't change anything. I followed the advice in #4293 to manually clone master, but it still gave me the same error. Finally I removed the `~/.cocoapods/repos/master` folder, which stopped giving me the above error.

However, now I'm getting the error below when I run `pod install`. The only terminal output beforehand was:

```
Re-creating CocoaPods due to major version update.
Setting up CocoaPods master repo
Setup completed
Unknown option: -C
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [-c name=value] [--help]
           <command> [<args>]
Unknown option: -C
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [-c name=value] [--help]
           <command> [<args>]
```
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 1.7.10.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f880f36fa2ce4bf0bd2ea86c2b19b24c992de51c
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'Literator' do
    pod 'RestKit', '~> 0.26.0'
    pod 'CocoaLumberjack'
    pod 'SSKeychain'
    # Copied into project because of a bug
    # pod 'DKTabPageViewController', '~> 1.4'
    pod 'SWRevealViewController', '~> 2.3'
    pod 'Charts', '~> 3.0'
    pod 'Google/SignIn'
    pod 'DateTools', '~> 1.7.0'
    pod 'FontAwesomeKit', :git => 'https://github.com/PrideChung/FontAwesomeKit.git'
    pod 'BFPaperButton'
    pod 'ARSPopover', '~>2.2.1'
    pod 'Mixpanel'
    pod 'FXLabel'
    pod 'SDWebImage', '~>3.7'
    pod 'JTSImageViewController', '1.5.1'
    pod 'FDTake'
    pod 'KLCPopup', '~>1.0'
    pod 'NSAttributedStringMarkdownParser', '~>0.0.1'
    pod 'MLPAutoCompleteTextField', '~>1.5'
    pod 'SlackTextViewController', '~>1.9.5'
end
```
### Error

```
RuntimeError - Unable to create a source with URL https://github.com/CocoaPods/Specs.git
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:42:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:814:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
Urg. This is likely `Dir.chdir` issue. Can you try re-running the command like this `FORK_XCODE_WRITING=true <cmd>`?

**Comment by benasher44** [comment]
This is fixed as part of #6048. Thanks for filing'

**Comment by jingidy** [comment]
It still seem to happen even when I pull cocoapods directly from master.

I used bundler with the following configuration:
```
source 'https://rubygems.org'

gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git', :branch => 'master'
```

That should get me the master branch version when I do `bundle install` then `bundle exec pod install` right? Still getting the same errors even after these steps.

**Comment by segiddins** [comment]
@jingidy you also need to grab Xcodeproj master

**Comment by jingidy** [comment]
I'm still getting the same errors, probably just missing something really simple.

Here's my Gemfile:
```
source 'https://rubygems.org'

gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git', :branch => 'master'
gem 'xcodeproj',  :git => 'https://github.com/CocoaPods/Xcodeproj.git', :branch=> 'master'
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git', :branch=> 'master'
```
Any other information I can provide that'd be helpful?

**Comment by benasher44** [comment]
Once you do that, can you do `bundle update cocoapods` and `bundle update xcodeproj`? Once that's done, can you show the contents of your Gemfile.lock?

**Comment by benasher44** [comment]
Also, make sure that when you run `pod install`, you run `bundle exec pod install` to be sure you're using the version installed in your bundle via the Gemfile.

**Comment by jingidy** [comment]
I ran the 2 update commands and used `bundle exec pod install` and I'm still getting the same errors 😟

But here's the Gemfile.lock!
```
GIT
  remote: https://github.com/CocoaPods/CocoaPods.git
  revision: eae884fbc1a3e1b9fb970f66e2ad04d0a9d925a9
  branch: master
  specs:
    cocoapods (1.1.1)
      activesupport (>= 4.0.2, < 5)
      claide (>= 1.0.1, < 2.0)
      cocoapods-core (= 1.1.1)
      cocoapods-deintegrate (>= 1.0.1, < 2.0)
      cocoapods-downloader (>= 1.1.2, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-stats (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.1.1, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored (~> 1.2)
      escape (~> 0.0.4)
      fourflusher (~> 2.0.1)
      gh_inspector (~> 1.0)
      molinillo (~> 0.5.1, != 0.5.2)
      nap (~> 1.0)
      ruby-macho (~> 0.2.5)
      xcodeproj (>= 1.3.3, < 2.0)

GIT
  remote: https://github.com/CocoaPods/Core.git
  revision: c64f9eb98ca18c92f00b649fe5ba20a6f35c34d0
  branch: master
  specs:
    cocoapods-core (1.1.1)
      activesupport (>= 4.0.2, < 5)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)

GIT
  remote: https://github.com/CocoaPods/Xcodeproj.git
  revision: 1e00e5991cd61d7e175943d0adafe527f6b2b253
  branch: master
  specs:
    xcodeproj (1.3.3)
      CFPropertyList (~> 2.3.3)
      activesupport (>= 3)
      claide (>= 1.0.1, < 2.0)
      colored (~> 1.2)
      nanaimo (~> 0.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.3)
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    claide (1.0.1)
    cocoapods-deintegrate (1.0.1)
    cocoapods-downloader (1.1.2)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.0)
    cocoapods-stats (1.0.0)
    cocoapods-trunk (1.1.1)
      nap (>= 0.8, < 2.0)
      netrc (= 0.7.8)
    cocoapods-try (1.1.0)
    colored (1.2)
    escape (0.0.4)
    fourflusher (2.0.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.0.2)
    i18n (0.7.0)
    json (1.8.3)
    minitest (5.9.1)
    molinillo (0.5.1)
    nanaimo (0.1.0)
    nap (1.1.0)
    netrc (0.7.8)
    ruby-macho (0.2.5)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  cocoapods!
  cocoapods-core!
  xcodeproj!

BUNDLED WITH
   1.13.6
```

**Comment by benasher44** [comment]
@segiddins do those look like the right commits?

**Comment by segiddins** [comment]
@benasher44 issue here is the git version is too old and doesn't have the `-C` option

**Comment by jingidy** [comment]
Haha, yes! once I upgraded git everything is 👌🏼

**Comment by benasher44** [comment]
Agreed.
