### ISSUE TITLE
Podfile.lock  can't be parsed after upgrade to 1.3.0

### ISSUE THREAD

**Issue by hijamoya** [CocoaPods/CocoaPods#6925]
# Report
Podfile.lock  can't be parsed after upgrade to 1.3.0. It works in 1.2.1.

## What did you do?
Run `pod install`

## What did you expect to happen?

Install successfully

## What happened instead?
```
[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at Podfile.lock
PODS:
  - !ProtoCompiler (3.2.0):
    - Protobuf (~> 3.0)
  - !ProtoCompiler-gRPCPlugin (1.3.0):
    - !ProtoCompiler (= 3.2.0)
    - gRPC-ProtoRPC (= 1.3.0)
  - Bolts (1.8.4):
    - Bolts/AppLinks (= 1.8.4)
    - Bolts/Tasks (= 1.8.4)
  - Bolts/AppLinks (1.8.4):
    - Bolts/Tasks
  - Bolts/Tasks (1.8.4)
  - BoringSSL (8.2):
    - BoringSSL/Implementation (= 8.2)
    - BoringSSL/Interface (= 8.2)
  - BoringSSL/Implementation (8.2):
    - BoringSSL/Interface (= 8.2)
  - BoringSSL/Interface (8.2)
  - Bugsnag (5.10.1):
    - KSCrash/RecordingAdvanced (= 1.8.13)
  - Charts (3.0.2):
    - Charts/Core (= 3.0.2)
  - Charts/Core (3.0.2)
  - DACircularProgress (2.3.1)
  - DatePickerDialog (1.1.7)
  - DKImagePickerController (3.5.5):
    - DKImagePickerController/Camera (= 3.5.5)
    - DKImagePickerController/ImageManager (= 3.5.5)
  - DKImagePickerController/Camera (3.5.5)
  - DKImagePickerController/ImageManager (3.5.5)
  - Down (0.3.4)
  - FBSDKCoreKit (4.16.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.16.0):
    - FBSDKCoreKit
  - Firebase/Auth (4.0.4):
    - Firebase/Core
    - FirebaseAuth (= 4.0.0)
  - Firebase/Core (4.0.4):
    - FirebaseAnalytics (= 4.0.2)
    - FirebaseCore (= 4.0.4)
  - Firebase/Database (4.0.4):
    - Firebase/Core
    - FirebaseDatabase (= 4.0.0)
  - Firebase/Storage (4.0.4):
    - Firebase/Core
    - FirebaseStorage (= 2.0.0)
  - FirebaseAnalytics (4.0.2):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseAuth (4.0.0):
    - FirebaseAnalytics (~> 4.0)
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (4.0.4):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseDatabase (4.0.0):
    - FirebaseAnalytics (~> 4.0)
  - FirebaseInstanceID (2.0.0):
    - FirebaseCore (~> 4.0)
  - FirebaseStorage (2.0.0):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FSCalendar (2.7.8)
  - GCDTimer (1.1.0)
  - GoogleAppUtilities (1.1.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleAuthUtilities (2.0.2):
    - GoogleNetworkingUtilities (~> 1.2)
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleNetworkingUtilities (1.2.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleSignIn (4.0.0):
    - GoogleAppUtilities (~> 1.1)
    - GoogleAuthUtilities (~> 2.0)
    - GoogleNetworkingUtilities (~> 1.2)
    - GoogleUtilities (~> 1.3)
  - GoogleSymbolUtilities (1.1.2)
  - GoogleToolboxForMac/DebugUtils (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/NSDictionary+URLArguments (2.1.1):
    - GoogleToolboxForMac/DebugUtils (= 2.1.1)
    - GoogleToolboxForMac/Defines (= 2.1.1)
    - GoogleToolboxForMac/NSString+URLArguments (= 2.1.1)
  - GoogleToolboxForMac/NSString+URLArguments (2.1.1)
  - GoogleUtilities (1.3.2):
    - GoogleSymbolUtilities (~> 1.1)
  - gRPC (1.3.0):
    - gRPC-Core (= 1.3.0)
    - gRPC-RxLibrary (= 1.3.0)
  - gRPC-Core (1.3.0):
    - gRPC-Core/Implementation (= 1.3.0)
    - gRPC-Core/Interface (= 1.3.0)
  - gRPC-Core/Implementation (1.3.0):
    - BoringSSL (~> 8.0)
    - gRPC-Core/Interface (= 1.3.0)
  - gRPC-Core/Interface (1.3.0)
  - gRPC-ProtoRPC (1.3.0):
    - gRPC (= 1.3.0)
    - gRPC-RxLibrary (= 1.3.0)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.3.0)
  - GTMSessionFetcher/Core (1.1.11)
  - JWTDecode (2.0.0)
  - Kanna (2.2.1)
  - Kingfisher (3.10.2)
  - KSCrash/Recording (1.8.13)
  - KSCrash/RecordingAdvanced (1.8.13):
    - KSCrash/Recording
  - KVNProgress (2.3.1)
  - MagicalRecord (2.3.2):
    - MagicalRecord/Core (= 2.3.2)
  - MagicalRecord/Core (2.3.2)
  - MBProgressHUD (0.9.2)
  - Mobile (0.0.25)
  - MWPhotoBrowser (2.1.2):
    - DACircularProgress (~> 2.3)
    - MBProgressHUD (~> 0.9)
    - SDWebImage (!= 3.7.2, ~> 3.7)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - PickerViewCell (0.1.0)
  - Protobuf (3.3.0)
  - ProtocolBuffers-Swift (3.0.16)
  - R.swift (3.3.0):
    - R.swift.Library (~> 3.0.2)
  - R.swift.Library (3.0.2)
  - ReachabilitySwift (3)
  - RxSwift (3.5.0)
  - SDWebImage (3.8.2):
    - SDWebImage/Core (= 3.8.2)
  - SDWebImage/Core (3.8.2)
  - SwiftBase32 (0.5.4)
  - Timepiece (0.5.0)
  - TOCropViewController (2.0.12)
  - TTTAttributedLabel (2.0.0)
  - UIColor_Hex_Swift (3.0.2)
  - UITextView+Placeholder (1.2.0)
  - XLPagerTabStrip (7.0.0)

DEPENDENCIES:
  - Bugsnag (= 5.10.1)
  - Charts (from `https://github.com/chiahan1123/Charts.git`)
  - DatePickerDialog (= 1.1.7)
  - DKImagePickerController (= 3.5.5)
  - Down (= 0.3.4)
  - FBSDKCoreKit (= 4.16.0)
  - FBSDKLoginKit (= 4.16.0)
  - Firebase/Auth
  - Firebase/Core
  - Firebase/Database
  - Firebase/Storage
  - FSCalendar (= 2.7.8)
  - GCDTimer (= 1.1.0)
  - GoogleSignIn (= 4.0.0)
  - gRPC (= 1.3.0)
  - JWTDecode (= 2.0.0)
  - Kanna (= 2.2.1)
  - Kingfisher (= 3.10.2)
  - KVNProgress (= 2.3.1)
  - MagicalRecord (= 2.3.2)
  - Mobile (from `Mobile/`)
  - MWPhotoBrowser (= 2.1.2)
  - PickerViewCell (from `https://github.com/hijamoya/PickerViewCell.git`)
  - Protobuf (= 3.3.0)
  - ProtocolBuffers-Swift (= 3.0.16)
  - R.swift (= 3.3.0)
  - ReachabilitySwift (= 3)
  - RxSwift (= 3.5.0)
  - SwiftBase32 (= 0.5.4)
  - Timepiece (from `https://github.com/skofgar/Timepiece.git`, branch `swift3`)
  - TOCropViewController (= 2.0.12)
  - TTTAttributedLabel (= 2.0.0)
  - UIColor_Hex_Swift (= 3.0.2)
  - UITextView+Placeholder (= 1.2)
  - XLPagerTabStrip (from `https://github.com/xmartlabs/XLPagerTabStrip.git`)

SPEC CHECKSUMS:
  !ProtoCompiler: b66c7c0c1d911ad1490dcbfce30e1508739d8309
  !ProtoCompiler-gRPCPlugin: 315d12febce749552558cbf93cf8eb4ed894777d
  Bolts: 8a7995239dbe724f9cba2248b766d48b7ebdd322
  BoringSSL: 4135ae556ee2b82ee85477c39ba917a3dd5424ba
  Bugsnag: 9c2d242eac7f215c40ff0f5813d378e9fcccf6e4
  Charts: e955b9a241a14a8971d70143002c8ab1610d26b6
  DACircularProgress: 4dd437c0fc3da5161cb289e07ac449493d41db71
  DatePickerDialog: bd5e7e92e4da2c6a8966b28d5f5d8f335d6c2c63
  DKImagePickerController: 16f28d10f4384d8c582aa05baab26fc75432a41d
  Down: 3f35b61e51a603df3e9e7e0289b15752e72f82e6
  FBSDKCoreKit: 7a6baaed4a2b2a244ba253346713bdbc74df135b
  FBSDKLoginKit: 9a514a55a7d05190f64d4ef09502737588b5b561
  Firebase: 1492bf04e1b73a7353b4fb2cf5a20bac9692f341
  FirebaseAnalytics: ad41720e3e67fc63fbe3d2948d3e26932a8de311
  FirebaseAuth: ebb6abcbabae00fc47446d690c19ce68d8484fde
  FirebaseCore: cfc042628ef9f20debe09c0eb683135fcd404cb4
  FirebaseDatabase: d829b3a8c3e2ac7a16773c5df226966b0805dfc2
  FirebaseInstanceID: 9fbf536668f4d3f0880e7438456dabd1376e294b
  FirebaseStorage: 8110a1ed2034c8fbfd83890d2acc9cdbbd99afec
  FSCalendar: 09369a2bf554ba71cd8e8cfb627e2df22a2c2af4
  GCDTimer: 5837a5d70a464f86cbc9c56d75efc68f7e7c2fb8
  GoogleAppUtilities: a8a552aa74f6597f805e45b5a3962766c3134973
  GoogleAuthUtilities: ccad2e0a9284699973ff57c0dd24c3893657fda4
  GoogleNetworkingUtilities: 3edd3a8161347494f2da60ea0deddc8a472d94cb
  GoogleSignIn: 09036ed61f8e75f1424100d63f7719480b2428c3
  GoogleSymbolUtilities: 631ee17048aa5e9ab133470d768ea997a5ef9b96
  GoogleToolboxForMac: 8e329f1b599f2512c6b10676d45736bcc2cbbeb0
  GoogleUtilities: 8bbc733218aad26306f9d4a253823986110e3358
  gRPC: c0d88992a7ceb367eb54afbabf6acdf36a7fd068
  gRPC-Core: d34ea5496af8d9640c38a9a6489557b9c7f58673
  gRPC-ProtoRPC: 9c46d1651690b5853e02f6ebda5aa8007d695193
  gRPC-RxLibrary: 9bc0b8c97518268573846ec846ed0ce50a8792c0
  GTMSessionFetcher: 5ad62e8200fa00ed011fe5e08d27fef72c5b1429
  JWTDecode: 178e47e5d28d3abcff778bacced8342858cd6cb5
  Kanna: 182789ab065e8f9a6ccc2a74ce6283d3401c0c4a
  Kingfisher: 7297492bf8cec9b2e2dee3519f2219948580d98e
  KSCrash: 4c3a83f133b60f4bd57e05235ebf8d46e36d378d
  KVNProgress: 8167b1f19e2758290c0b6143020ed9dcbb0477a1
  MagicalRecord: 53bed74b4323b930992a725be713e53b37d19755
  MBProgressHUD: 1569cf7ace17a8bac47aabfbb8580a49690386d1
  Mobile: 3f246151a994eaaf7318593723232eaee43645f5
  MWPhotoBrowser: 5836d7aa041dc05a13de380c246826578adc5ea5
  nanopb: 5601e6bca2dbf1ed831b519092ec110f66982ca3
  PickerViewCell: 4e6987bc69348a11782d8a3f711a684b8a320e9b
  Protobuf: d582fecf68201eac3d79ed61369ef45734394b9c
  ProtocolBuffers-Swift: cba3f101c408355bb2a426c8d14c63cf2de3f567
  R.swift: bde9704d50ff36820f49e266bc88ef545e1e9b36
  R.swift.Library: fbdec16c9802ad104fc1ba53415dc190e6ec5c73
  ReachabilitySwift: f5b9bb30a0777fac8f09ce8b067e32faeb29bb64
  RxSwift: 18ee9d78b45edb3b0b7e79916b47a116e6dbc842
  SDWebImage: 098e97e6176540799c27e804c96653ee0833d13c
  SwiftBase32: 5145942008e31f60c2d1b57e4082335713b74ce5
  Timepiece: c8360276f0aa935bfb0e53f8ed38abe41c93b5b4
  TOCropViewController: e6e31b38d785a901e5651a1e7fff71bcda6c5214
  TTTAttributedLabel: 8cffe8e127e4e82ff3af1e5386d4cd0ad000b656
  UIColor_Hex_Swift: 95f718452092a3efc8a827dffd2c04d3237be02d
  UITextView+Placeholder: 77680995fcdd07c3f52ec92fe1150874a2ac89ff
  XLPagerTabStrip: 6e2cc6753041c3c720d23a9ff3606cb58325d754

PODFILE CHECKSUM: 2385dc4e6e25393a52d5fdab3a75d248105ab9af

COCOAPODS: 1.3.0
```

**Comment by dnkoutso** [comment]
I believe that is because of 
```
!ProtoCompiler: b66c7c0c1d911ad1490dcbfce30e1508739d8309
!ProtoCompiler-gRPCPlugin: 315d12febce749552558cbf93cf8eb4ed894777d
```

But I still see the same error with CocoaPods 1.2.1

**Comment by dnkoutso** [comment]
@segiddins any thoughts on this? I can repro in 1.2.1, surprised noone has complained about this before

**Comment by segiddins** [comment]
yeah, we should be banning `!` in pod names. in the meantime I guess I can look into fixing up the yaml serializer to fix it? Since that's invalid YAML

**Comment by dnkoutso** [comment]
This is the reason it includes an exclamation mark:

https://github.com/grpc/grpc/blob/master/src/objective-c/!ProtoCompiler.podspec#L33-L37

**Comment by segiddins** [comment]
What's the output when you run `ruby -rpsych -e 'puts Psych::VERSION'` ? Since I can't reproduce this with psych 2.2.2

**Comment by dnkoutso** [comment]
For me its `2.0.5`

**Comment by segiddins** [comment]
https://github.com/CocoaPods/Core/pull/395 should fix this in the future by improving our YAML serialization

**Comment by ondev** [comment]
How to upgrade to 1.3.0?

**Comment by hijamoya** [comment]
sudo gem install cocoapods -v 1.3.0

**Comment by mamouneyya** [comment]
I can still reproduce the mentioned issue in versions `1.3.1` && `1.4.0.beta.1`

A simple `Podfile` to try with:
```
platform :ios, '8.0'

use_frameworks!

def broken_pods
    pod '!ProtoCompiler'
end

target 'demo' do
    broken_pods
end

target 'demoTests' do
    broken_pods
end
```

Here is the generated `Podfile.lock`:
```
PODS:
  - !ProtoCompiler (3.4.0):
    - Protobuf (~> 3.0)
  - Protobuf (3.4.0)

DEPENDENCIES:
  - !ProtoCompiler

SPEC CHECKSUMS:
  !ProtoCompiler: 07d0c441bc00e7f01e84debf7c53794683fbca7c
  Protobuf: 03eef2ee0b674770735cf79d9c4d3659cf6908e8

PODFILE CHECKSUM: 808b2a2377c269d78ea0d65736dc561634737726

COCOAPODS: 1.4.0.beta.1
```

**Comment by 0oneo** [comment]
me too
```
PODS:
  - !ProtoCompiler (3.4.0):
    - Protobuf (~> 3.0)
  - !ProtoCompiler-gRPCPlugin (1.6.5):
    - !ProtoCompiler (= 3.4.0)
    - gRPC-ProtoRPC (= 1.6.5)
  - AFNetworking (3.1.0):
    - AFNetworking/NSURLSession (= 3.1.0)
    - AFNetworking/Reachability (= 3.1.0)
    - AFNetworking/Security (= 3.1.0)
    - AFNetworking/Serialization (= 3.1.0)
    - AFNetworking/UIKit (= 3.1.0)
  - AFNetworking/NSURLSession (3.1.0):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (3.1.0)
  - AFNetworking/Security (3.1.0)
  - AFNetworking/Serialization (3.1.0)
  - AFNetworking/UIKit (3.1.0):
    - AFNetworking/NSURLSession
  - gRPC (1.6.5):
    - gRPC-Core (= 1.6.5)
    - gRPC-RxLibrary (= 1.6.5)
  - gRPC-Core (1.6.5):
    - gRPC-Core/Implementation (= 1.6.5)
    - gRPC-Core/Interface (= 1.6.5)
  - gRPC-Core/Implementation (1.6.5):
    - BoringSSL (~> 9.0)
    - gRPC-Core/Interface (= 1.6.5)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.6.5)
  - gRPC-ProtoRPC (1.6.5):
    - gRPC (= 1.6.5)
    - gRPC-RxLibrary (= 1.6.5)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.6.5)
  - GZIP (1.2.1)

SPEC CHECKSUMS:
  !ProtoCompiler: 07d0c441bc00e7f01e84debf7c53794683fbca7c
  !ProtoCompiler-gRPCPlugin: dfc8eead3e132b22750b0ec7f5fe4774ef98362a
  AFNetworking: 5e0e199f73d8626b11e79750991f5d173d1f8b67
  BlocksKit: 7f422b971407001178d181a43b99014ea2591fe6
  BoringSSL: 19083b821ef3ae0f758fae15482e183003b1e265
  CocoaLumberjack: aa9dcab71bdf9eaf2a63bbd9ddc87863efe45457
  Geohash: a4a406a469802862394f83d3f2a5135b3eca4730
  gRPC: 42f915ce322b1abc5241621acc776f2fdb0a2039
  gRPC-Core: 54211a073d238ec8569be06e1a939a72f081a3e9
  gRPC-ProtoRPC: 4299db62f86df58c88844ccb50f5c48993e704f6
  gRPC-RxLibrary: 1b1c9c9cf666709ad7714cb0e0f3c44dc0cbfb0b
  GZIP: 7ee835f989fb3c6ea79005fc90b8fa6af710a70d
  libextobjc: a650fc1bf489a3d3a9bc2e621efa3e1006fc5471
  Mantle: 2fa750afa478cd625a94230fbf1c13462f29395b
  nanopb: 5601e6bca2dbf1ed831b519092ec110f66982ca3
  Protobuf: 03eef2ee0b674770735cf79d9c4d3659cf6908e8
  RegExCategories: e68befacacd5bda853c88f70ec745cb2d0cfb89c
  SAMKeychain: 483e1c9f32984d50ca961e26818a534283b4cd5c

PODFILE CHECKSUM: 40bbff9feda84ae7db17d65d2ffca41edbfa36a4

COCOAPODS: 1.3.1
```

**Comment by 0oneo** [comment]
any news about this， I have tried 1.4 beta1 and beta2, the problem is still there

**Comment by orta** [comment]
Dupe of https://github.com/CocoaPods/CocoaPods/issues/6955
