### ISSUE TITLE
`frameworks` from `test_spec` are leaking into the main spec

### ISSUE THREAD

**Issue by adc-amatosov** [CocoaPods/CocoaPods#7172]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
`frameworks` from `test_spec` are leaking into the main spec

## What did you do?
Created pod with `test_spec` and added `frameworks` to `spec` and `test_spec`
```
Pod::Spec.new do |s|
  s.name             = 'TestSpecs'

  s.frameworks = "Accelerate"

  s.test_spec "Tests" do |ts|
    ts.frameworks = "CoreTelephony"
```

## What did you expect to happen?
`test_spec` specific `frameworks` should be linked only to test target, not the framework target

`Example/Pods/Target Support Files/TestSpecs/TestSpecs.xcconfig` should have only:
`OTHER_LDFLAGS = -framework "Accelerate"`
and framework target should link only to `Accelerate`, but not `CoreTelephony`

## What happened instead?
`frameworks` from `test_spec` are linked to test target and pod's framework target

`Example/Pods/Target Support Files/TestSpecs/TestSpecs.xcconfig` contains:
`OTHER_LDFLAGS = -framework "Accelerate" -framework "CoreTelephony"`
as well as `TestSpecs` framework target has both `Accelerate` and `CoreTelephony`

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13 (17A405)
       Xcode : 9.0 (9A235)
         Git : git version 2.10.2
Ruby lib dir : /Users/amatosov.ctr/.rbenv/versions/2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b0f5668dcff321e5a062f17d16152d3e0bbeb41c
```

### Installation Source

```
Executable Path: /Users/amatosov.ctr/.rbenv/versions/2.2.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, "11"
use_frameworks!

target 'TestSpecs_Dummy' do
  pod 'TestSpecs', :path => '../', :testspecs => ["Tests"]

end
```

## Project that demonstrates the issue
https://github.com/adc-amatosov/TestSpecs/tree/linking_frameworks.

`https://github.com/adc-amatosov/TestSpecs.git` branch `linking_frameworks`

**Comment by dnkoutso** [comment]
This is fixed with 1.4.0.beta.2

**Comment by dnkoutso** [comment]
Please try it and if you see it not working I will re-open this here.

**Comment by adc-amatosov** [comment]
Great! I will check it out later today

**Comment by adc-amatosov** [comment]
I have verified with 1.4.0.beta2 and issue still exists there

**Comment by dnkoutso** [comment]
Thanks will take a look.

**Comment by adc-amatosov** [comment]
Thank you

**Comment by dnkoutso** [comment]
@adc-amatosov I opened a PR with the fix. Can you locally try it also and verify it works?

**Comment by adc-amatosov** [comment]
Checking it right now

**Comment by dnkoutso** [comment]
Looks correct to me btw:
```diff
git diff "Pods/Target Support Files/TestSpecs/TestSpecs.xcconfig"
diff --git a/Example/Pods/Target Support Files/TestSpecs/TestSpecs.xcconfig b/Example/Pods/Target Support Files/TestSpecs/TestSpecs.xcconfig
index af85c3b..a1af17b 100644
--- a/Example/Pods/Target Support Files/TestSpecs/TestSpecs.xcconfig    
+++ b/Example/Pods/Target Support Files/TestSpecs/TestSpecs.xcconfig    
@@ -2,7 +2,7 @@ CONFIGURATION_BUILD_DIR = ${PODS_CONFIGURATION_BUILD_DIR}/TestSpecs
 FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/ReactiveCocoa" "${PODS_CONFIGURATION_BUILD_DIR}/ReactiveSwift" "${PODS_CONFIGURATION_BUILD_DIR}/Result"
 GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
 HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Public"
-OTHER_LDFLAGS = -framework "Accelerate" -framework "CoreTelephony"
+OTHER_LDFLAGS = -framework "Accelerate"
 OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
 PODS_BUILD_DIR = ${BUILD_DIR}
 PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
```

**Comment by adc-amatosov** [comment]
Verified. This change solves the issue!

**Comment by amorde** [comment]
@adc-amatosov Thanks for the write up! I had noticed this issue on our project as well but didn't get around to creating an example project + issue 👍

**Comment by adc-amatosov** [comment]
you are welcome

**Comment by dnkoutso** [comment]
thank you both. Will be merging this shortly.
