### ISSUE TITLE
Testing failed: The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift.

### ISSUE THREAD

**Issue by stalinkay** [CocoaPods/CocoaPods#7229]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod lib lint --sources=git@gitlab.com:stalinkaydev/sk-commerce-kit.git,master --allow-warnings --verbose`

## What did you expect to happen?

Run Unit Tests

## What happened instead?

Testing Failed:

```
Testing failed:
        The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
** TEST FAILED **


The following build commands failed:
        Check dependencies
        Check dependencies
(2 failures)
 -> SKCommerceKit (0.1.0)
    - WARN  | description: The description is shorter than the summary.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

[!] SKCommerceKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
```

### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.13.1 (17B48)
       Xcode : 9.1 (9B55)
         Git : git version 2.11.1
Ruby lib dir : /usr/local/Cellar/ruby/2.4.0/lib
Repositories : gitlab-sk-commerce-kit - git@gitlab.com:stalinkaydev/sk-commerce-kit.git @ 171d2fad11d229fe898ffb1332cefaa07a943e39
               master - https://github.com/CocoaPods/Specs.git @ eb81fcfbd0dc2fffedff0de1ba19e8c5e56415bd
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

use_frameworks!

target 'SKCommerceKit_Example' do
  pod 'SKCommerceKit', :path => '../', :testspecs => ['Tests']

  target 'SKCommerceKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

### Framework Podspec

```
Pod::Spec.new do |s|
  s.name             = 'SKCommerceKit'
  s.version          = '0.1.0'
  s.summary          = 'This is the official Stalin Kay Commerce Kit. This can be used to develop e-commerce apps.'

  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC

  s.homepage         = 'https://gitlab.com/stalinkaydev/sk-commerce-kit'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'stalinkay' => 'stalin@stalinkay.com' }
  s.source           = { :git => 'https://gitlab.com/stalinkaydev/sk-commerce-kit.git', :tag => s.version.to_s }
  s.social_media_url = 'https://twitter.com/stalinkay'

  s.ios.deployment_target = '8.0'

  s.source_files = 'SKCommerceKit/Classes/**/*'
  s.test_spec 'Tests' do |test_spec|
    test_spec.source_files = 'SKCommerceKit/Tests/**/*'
    test_spec.dependency 'Quick'
    test_spec.dependency 'Nimble'
  end
  # s.resource_bundles = {
  #   'SKCommerceKit' => ['SKCommerceKit/Assets/*.png']
  # }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  # s.dependency 'AFNetworking', '~> 2.3'
end
```

### Project Structure

```
.
├── Cartfile
├── Cartfile.private
├── Example
│   ├── Podfile
│   ├── Podfile.lock
│   ├── Pods
│   │   ├── FBSnapshotTestCase
│   │   ├── Local\ Podspecs
│   │   ├── Manifest.lock
│   │   ├── Nimble
│   │   ├── Nimble-Snapshots
│   │   ├── Pods.xcodeproj
│   │   ├── Quick
│   │   └── Target\ Support\ Files
│   ├── SKCommerceKit
│   │   ├── AppDelegate.swift
│   │   ├── Base.lproj
│   │   ├── Images.xcassets
│   │   ├── Info.plist
│   │   └── ViewController.swift
│   ├── SKCommerceKit.xcodeproj
│   │   ├── project.pbxproj
│   │   ├── project.xcworkspace
│   │   └── xcshareddata
│   ├── SKCommerceKit.xcworkspace
│   │   └── contents.xcworkspacedata
│   └── Tests
│       ├── Info.plist
│       └── Tests.swift
├── Gemfile
├── Gemfile.lock
├── LICENSE
├── README.md
├── SKCommerceKit
│   ├── Assets
│   ├── Classes
│   │   ├── Beat.swift
│   │   └── Purchasable.swift
│   └── Tests
│       └── BeatSpec.swift
├── SKCommerceKit.podspec
├── _Pods.xcodeproj -> Example/Pods/Pods.xcodeproj
├── bin
│   └── setup
├── docs
│   ├── Protocols.html
│   ├── badge.svg
│   ├── css
│   │   ├── highlight.css
│   │   └── jazzy.css
│   ├── docsets
│   │   └── SKCommerceKit.docset
│   ├── img
│   │   ├── carat.png
│   │   ├── dash.png
│   │   └── gh.png
│   ├── index.html
│   ├── js
│   │   ├── jazzy.js
│   │   └── jquery.min.js
│   ├── search.json
│   └── undocumented.json
├── fastlane
│   ├── Fastfile
│   └── README.md
├── lint.sh
├── package-lock.json
├── package.json
├── spellcheck
└── spellcheck.sh

30 directories, 40 files
```

**Comment by dnkoutso** [comment]
Thanks can you attach the sample project you have in a zip or a git repo?

**Comment by stalinkay** [comment]
@dnkoutso Find attached zip below.

[SKCommerceKit.zip](https://github.com/CocoaPods/CocoaPods/files/1485745/SKCommerceKit.zip)

**Comment by dnkoutso** [comment]
@stalinkay I was unable to reproduce. I am seeing correct swift version set for unit test target and the pod.

**Comment by dnkoutso** [comment]
@stalinkay my bad, I was working with latest version of master and thats why I couldn't. This issue has been fixed. You may use bundler to point to a specific SHA of CocoaPods until 1.4.0.rc.1 is released.

Please note you will have to fix the missing `LICENSE` file in your podspec as I found out in my testing.

Going to close this but feel free to leave a comment if something still not working.

**Comment by stalinkay** [comment]
Thanks for the feedback @dnkoutso. Which SHA should I use or should I try the 1.4-stable branch?

**Comment by dnkoutso** [comment]
latest is fine, 3fe4b32a9c3a00635383521affe9484c48cf5add

**Comment by stalinkay** [comment]
Cool. Thanks.

**Comment by stalinkay** [comment]
@dnkoutso It's still failing on my end, here's my full repo zipped. Try running `bundle exec pod lib lint --sources=git@gitlab.com:stalinkaydev/sk-commerce-kit.git,master --allow-warnings --verbose`. Find attached zip below.

[SKCommerceKit.zip](https://github.com/CocoaPods/CocoaPods/files/1486869/SKCommerceKit.zip)

**Comment by stalinkay** [comment]
@dnkoutso This is what I'm getting.

```
Testing failed:
        The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
** TEST FAILED **


The following build commands failed:
        Check dependencies
        Check dependencies
(2 failures)
 -> SKCommerceKit (0.1.0)
    - WARN  | description: The description is shorter than the summary.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

[!] SKCommerceKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
```

**Comment by stalinkay** [comment]
@dnkoutso Also `git checkout 3-add-beat`
