### ISSUE TITLE
Malformed version number string

### ISSUE THREAD

**Issue by zedixns** [CocoaPods/CocoaPods#7765]
# Report

## What did you do?
pod install

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?
ArgumentError - Malformed version number string

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/jenkins/.rvm/rubies/ruby-2.5.1/lib
Repositories :
               master - https://github.com/CocoaPods/Specs.git @fab7726d367d90b163a793e2f6419b69ee9b93c5
```

### Installation Source

```
Executable Path: /Users/jenkins/.rvm/gems/ruby-2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'

def pods
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'CocoaLumberjack'
    pod 'SSZipArchive'
    pod 'ActionSheetPicker-3.0', '~> 2.2.0'
end

target 'projectdemo' do
    pods
end

target 'projectdemoStaging' do
    pods
end

target 'projectdemoDebug' do
    pods
end

target 'projectdemoMock' do
    pods
end
```

## Project that demonstrates the issue

##Additional details

Adding a --verbose flag to the install command gives a little bit more insight into what happened.

```
Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `ActionSheetPicker-3.0` iOS 4.3
    - Installing target `CocoaLumberjack` iOS 6.0
    - Installing target `SSZipArchive` iOS 4.0
    - Installing target `Pods-projectdemo` iOS 8.0
```

As you can see at the end when it does the project setup, it adds the targets with magic quotes which break the build.

**Comment by darkThanBlack** [comment]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.3.1 (9E501)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!

target 'GrandRoutes' do

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage'
pod 'Masonry', '~> 1.1.0'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'MBProgressHUD'
pod 'MJExtension', '~> 3.0.13'
pod 'DoImagePickerController', '~> 1.6'
pod 'Realm'
pod 'IQKeyboardManager', '~> 4.0.5'
pod 'TOCropViewController', '~> 2.0.7'
pod 'AXWebViewController', '~> 0.3.3'
pod 'BaiduMapKit', '~> 3.0.0'
pod 'SDCycleScrollView'
pod 'Meiqia'
pod 'FDFullscreenPopGesture'
pod 'CocoaAsyncSocket'
pod 'ZLPhotoBrowser'
pod "MWPhotoBrowser", :podspec =>'https://raw.githubusercontent.com/moinku07/MWPhotoBrowser/master/MWPhotoBrowser.podspec'
pod 'ZFPlayer'

end
```

### Error

```
ArgumentError - Malformed version number string
/Library/Ruby/Site/2.3.0/rubygems/version.rb:209:in `initialize'
/Library/Ruby/Site/2.3.0/rubygems/version.rb:200:in `new'
/Library/Ruby/Site/2.3.0/rubygems/version.rb:200:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:123:in `embedded_content_settings'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:68:in `generate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:112:in `update_changed_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:96:in `block in create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:181:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `block in install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:167:in `install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Malformed version number string
   https://github.com/CocoaPods/CocoaPods/issues/7765 [open] [0 comments]
   9 minutes ago

 - ArgumentError - Malformed version number string $(inherited)
   https://github.com/CocoaPods/CocoaPods/issues/6634 [closed] [5 comments]
   3 hours ago

 - help!
   https://github.com/CocoaPods/CocoaPods/issues/7763 [open] [1 comment]
   2 minutes ago

and 29 more at:
https://github.com/cocoapods/cocoapods/search?q=Malformed%20version%20number%20string%20&type=Issues&utf8=✓

**Comment by darkThanBlack** [comment]
also 'Malformed version number string'...OMG...

**Comment by DanToml** [comment]
@zedixns / @darkThanBlack It looks like this is crashing while trying to resolve the target swift version - Could you share an Xcode project that reproduces this please?

**Comment by zedixns** [comment]
@DanToml Unfortunately I am not able to share the project, because it's commercial.

**Comment by DanToml** [comment]
@zedixns Unfortunately the only way I can work on this further is with a full repro case (and I don't currently have a recent version of Xcode around to try creating projects with).

The bare minimum we'd need would be a `grep -i swift_version ./my-project.xcodeproj/project.pbxproj`

**Comment by zedixns** [comment]
@DanToml 
The output is:
```
SWIFT_VERSION = 3.0;
SWIFT_VERSION = 3.0;
SWIFT_VERSION = 3.0;
SWIFT_VERSION = 3.0;
```

I have to note here that the actual project doesn't have any swift code in it. Don't know if that makes any difference.

**Comment by eploko** [comment]
I haven't had the issue locally, but stumbled upon it in a Travis build. Turns out I can reproduce this locally by just updating to the latest rubygems.

`bundle exec pod install` fails with RubyGems 2.7.7, but works fine with 2.7.6.

**Comment by dnkoutso** [comment]
Can you please try with CocoaPods master using https://bundler.io/?

**Comment by dnkoutso** [comment]
Yes we really need a sample project here demonstrating the issue. It will help debug it.

**Comment by segiddins** [comment]
Looks to be caused by the rubygems 2.7.7 release: https://github.com/rubygems/rubygems/compare/v2.7.6...v2.7.7#diff-94d386526b8b558035d4e4c7602d647cR173

**Comment by dnkoutso** [comment]
This appears to be fixed on master, we will most likely do a 1.5.3 release.

**Comment by LuXiong** [comment]
I also encountered this issue. And I tried to start a new project, but the issue still exist while using pod install.

**Comment by LuXiong** [comment]
bogon:PodTest deven$ pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (3.2.1)
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3.1 (9E501)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : bigo-bigo-specs - http://gitlab.bigo.sg:8081/Bigo/Specs.git @ f2ad4499275f6a433c0aca874dc1c2b066e86c96
               master - https://github.com/CocoaPods/Specs.git @ a35415c0686f8d02dce098fa7b3657ff0f475d50
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PodTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PodTest
  pod 'AFNetworking'

  target 'PodTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
ArgumentError - Malformed version number string 
/Library/Ruby/Site/2.3.0/rubygems/version.rb:209:in `initialize'
/Library/Ruby/Site/2.3.0/rubygems/version.rb:200:in `new'
/Library/Ruby/Site/2.3.0/rubygems/version.rb:200:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:123:in `embedded_content_settings'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:68:in `generate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:112:in `update_changed_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:96:in `block in create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:181:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `block in install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:167:in `install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Malformed version number string
   https://github.com/CocoaPods/CocoaPods/issues/7765 [open] [12 comments]
   4 hours ago

 - ArgumentError - Malformed version number string $(inherited)
   https://github.com/CocoaPods/CocoaPods/issues/6634 [closed] [5 comments]
   20 hours ago

 - help!
   https://github.com/CocoaPods/CocoaPods/issues/7763 [closed] [2 comments]
   15 hours ago

and 31 more at:
https://github.com/cocoapods/cocoapods/search?q=Malformed%20version%20number%20string%20&type=Issues&utf8=✓

**Comment by dnkoutso** [comment]
It's been fixed, there is a PR for it.

**Comment by xngockhoix** [comment]
How can I get that fixed version?

**Comment by sofienB** [comment]
I have same issue :(

**Comment by LuXiong** [comment]
I solved the problem by upgrading my ruby and reinstall the cocoa pod

**Comment by huangshoumin** [comment]
I also encountered this problem, and tried the following steps to solve it:

1. Brew update instructions update Homebrew(because there is no prompt, it will wait for a while to be completed)
2. Install RVM
3. Use RVM to install the latest version of ruby(this time using ruby-2.4.1)
4. Use the command sudo gem install -n /usr/local/bin cocoapods to reload cocoapods.

The problem is fixed

**Comment by sofienB** [comment]
I resolved this issue by downgrade gem with this commande line : `update_rubygems _2.7.6_`

**Comment by hujifenggg** [comment]
CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)

### Error

```
ArgumentError - Malformed version number string 
/Library/Ruby/Site/2.3.0/rubygems/version.rb:209:in `initialize'
/Library/Ruby/Site/2.3.0/rubygems/version.rb:200:in `new'
/Library/Ruby/Site/2.3.0/rubygems/version.rb:200:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:123:in `embedded_content_settings'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:68:in `generate'


help me，thanks！

**Comment by LuXiong** [comment]
@hujifenggg you can try to upgrade your ruby to 2.4.1 and reinstall your cocoa pod

**Comment by hujifenggg** [comment]
@LuXiong thanks！

**Comment by segiddins** [comment]
This should now be fixed in CocoaPods 1.5.3!

**Comment by zedixns** [comment]
@segiddins @DanToml @dnkoutso 
Thank you very much for the assistance and the fix!

I can confirm that the issue has been fixed. So this thread can be closed.

**Comment by iPermanent** [comment]
maybe you used rvm to update the system ruby version?
I get this issue and fixed it by uninstall all cocoa pods and then install it.
first rvm list all --local
them use rvm uninstall to uninstall all items listed named with cocoapods prefix,
and then exit the terminal, reopen it ,list again until no items names contains cocoapods, then you can install it with a new way

**Comment by KumMadhu** [comment]
I am facing this error with CocoaPod version 1.7.2 and Xcode 9.4.x (including betas), installed on macOS 10.13 (High Sierra). Previously CocoaPod installation step was working fine with Xcode 9.2.*

**Comment by paulb777** [comment]
@KumMadhu There is no version 1.7.2. Check the CocoaPods version with `pod --version`

**Comment by tanpengsccd** [comment]
maybe it's xcode 10 beta .
pod lib lint   
get the error
```
- ERROR | [iOS] unknown: Encountered an unknown error (Malformed version number string ) during validation.
```
I installed Xcode  9.4.1  and  10beta ,then I uninstall 10beta.  Pass it

**Comment by kukushi** [comment]
@tanpengsccd 
It works!
Temporarily put Xcode 10 into Trash solve this issue.

**Comment by StrongX** [comment]
gem 2.7.7 can not run cocoapods 1.3.x . 1.4.x
you should install rubygem in 2.7.6
please:
gem install rubygems-update -v 2.7.6
and
update_rubygems


then
pod install or pod update

**Comment by LDKFighter** [comment]
i fixed it.
@StrongX 

gem 2.7.7 can not run cocoapods 1.3.x . 1.4.x
you should install rubygem in 2.7.6
please:
gem install rubygems-update -v 2.7.6
and
update_rubygems

then
pod install or pod update

Successed

**Comment by BaihaoTian** [comment]
if your rubyGems version is 2.7.7 or higher  you just can do like this 
`gem update --system 2.7.6`
my problem has resolved by doing this.

**Comment by gongzelong0718** [comment]
```
admindeMacBook-Pro:mall-ios gongzelong$ gem --debug update --system 2.7.6
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/resolv.rb:168 - LoadError
Exception `Errno::EEXIST' at /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:252 - File exists @ dir_s_mkdir - /Users/gongzelong/.gem/specs/api.rubygems.org%443
Exception `Errno::ENOENT' at /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:325 - No such file or directory @ rb_file_s_stat - /Users/gongzelong/.gem/specs/api.rubygems.org%443/specs.4.8
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/buffering.rb:182 - read would block
^CException `Interrupt' at /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:155 - 
ERROR:  Interrupted
```

```
### Command



```

/Users/gongzelong/.rvm/gems/ruby-2.2.0/bin/pod install

```



### Report



* What did you do?



* What did you expect to happen?



* What happened instead?





### Stack



```

   CocoaPods : 1.2.1

        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin17]

    RubyGems : 2.7.7

        Host : Mac OS X 10.13.6 (17G65)

       Xcode : 9.4.1 (9F2000)

         Git : git version 2.15.2 (Apple Git-101.1)

Ruby lib dir : /Users/gongzelong/.rvm/rubies/ruby-2.2.0/lib
```
```
admindeMacBook-Pro:mall-ios gongzelong$ gem install rubygems-update -v 2.7.6
admindeMacBook-Pro:mall-ios gongzelong$ update_rubygems
```

@LDKFighter thanks, it works for me.

**Comment by Hanten** [comment]
Maybe you can update ruby to 2.4+

**Comment by wjyx1lalala** [comment]
i had fixed by:   sudo gem update --system 2.7.6

**Comment by TarunNarula** [comment]
I am stuck on it from so many hours, tried everything:

Taruns-MacBook-Air:ios tarunnarula$ pod install
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A255)
         Git : git version 2.15.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 82a0a895a73c99fe6e28cfa4458205ba828706f3
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'kosara' do
  # React Native third party dependencies podspecs for Kosara

  # Required by RNFirebase
  pod 'Firebase/Core'
  #pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
```

### Error

```
ArgumentError - Malformed version number string ~> 5.0.1
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/version.rb:54:in `initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:154:in `name_and_version_from_string'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:214:in `block in generate_pod_names_and_versions'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:212:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:212:in `generate_pod_names_and_versions'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:240:in `pod_versions'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:87:in `version'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:168:in `block in dependencies_to_lock_pod_named'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:167:in `map'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:167:in `dependencies_to_lock_pod_named'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:296:in `block in detect_changes_with_podfile'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:294:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:294:in `detect_changes_with_podfile'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:233:in `block in generate_podfile_state'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:232:in `generate_podfile_state'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:82:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+~%3E+5.0.1&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - iOS framework addition failed due to a Cocoapods installation failure.
   https://github.com/CocoaPods/CocoaPods/issues/7767 [closed] [1 comment]
   22 May 2018

 - Malformed version number string Base.lproj
   https://github.com/CocoaPods/CocoaPods/issues/1582 [closed] [1 comment]
   12 Nov 2013

 - Pod install failed unexpectedly 
   https://github.com/CocoaPods/CocoaPods/issues/1544 [closed] [1 comment]
   11 Nov 2013

Support will be appreciated

**Comment by iPermanent** [comment]
> I am stuck on it from so many hours, tried everything:
> 
> Taruns-MacBook-Air:ios tarunnarula$ pod install
> Analyzing dependencies
> 
> ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> ### Command
> ```
> /usr/local/bin/pod install
> ```
> ### Report
> * What did you do?
> * What did you expect to happen?
> * What happened instead?
> 
> ### Stack
> ```
>    CocoaPods : 1.5.3
>         Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
>     RubyGems : 2.7.6
>         Host : Mac OS X 10.13.6 (17G65)
>        Xcode : 10.0 (10A255)
>          Git : git version 2.15.0
> Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
> Repositories : master - https://github.com/CocoaPods/Specs.git @ 82a0a895a73c99fe6e28cfa4458205ba828706f3
> ```
> ### Plugins
> ```
> cocoapods-deintegrate : 1.0.2
> cocoapods-plugins     : 1.0.0
> cocoapods-search      : 1.0.0
> cocoapods-stats       : 1.0.0
> cocoapods-trunk       : 1.3.1
> cocoapods-try         : 1.1.0
> ```
> ### Podfile
> ```ruby
> # Uncomment the next line to define a global platform for your project
> platform :ios, '9.0'
> 
> target 'kosara' do
>   # React Native third party dependencies podspecs for Kosara
> 
>   # Required by RNFirebase
>   pod 'Firebase/Core'
>   #pod 'Firebase/Firestore'
>   pod 'Firebase/Messaging'
> 
>   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
> 
> end
> ```
> 
> ### Error
> ```
> ArgumentError - Malformed version number string ~> 5.0.1
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/version.rb:54:in `initialize'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:154:in `name_and_version_from_string'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:214:in `block in generate_pod_names_and_versions'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:212:in `each'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:212:in `generate_pod_names_and_versions'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:240:in `pod_versions'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:87:in `version'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:168:in `block in dependencies_to_lock_pod_named'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:167:in `map'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:167:in `dependencies_to_lock_pod_named'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:296:in `block in detect_changes_with_podfile'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:294:in `each'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:294:in `detect_changes_with_podfile'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:233:in `block in generate_podfile_state'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:232:in `generate_podfile_state'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:82:in `analyze'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
> /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'
> ```
> ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> [!] Oh no, an error occurred.
> 
> Search for existing GitHub issues similar to yours:
> [https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+~%3E+5.0.1&type=Issues](https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+%7E%3E+5.0.1&type=Issues)
> 
> If none exists, create a ticket, with the template displayed above, on:
> https://github.com/CocoaPods/CocoaPods/issues/new
> 
> Be sure to first read the contributing guide for details on how to properly submit a ticket:
> https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
> 
> Don't forget to anonymize any private data!
> 
> Looking for related issues on cocoapods/cocoapods...
> 
> * iOS framework addition failed due to a Cocoapods installation failure.
>   #7767 [closed] [1 comment]
>   22 May 2018
> * Malformed version number string Base.lproj
>   #1582 [closed] [1 comment]
>   12 Nov 2013
> * Pod install failed unexpectedly
>   #1544 [closed] [1 comment]
>   11 Nov 2013
> 
> Support will be appreciated

maybe you have installed the bundler?  
you can run : gem list --local
and then : gem uninstall cocoapods-xxx to install all things that have cocoapods prefix
and last sudo gem install cocoapods

**Comment by TarunNarula** [comment]
@iPermanent Thank you very much for replying, I have done the same but still facing the same error:

Taruns-MacBook-Air:ios tarunnarula$ pod install
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A255)
         Git : git version 2.15.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 82a0a895a73c99fe6e28cfa4458205ba828706f3
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'kosara' do
  # React Native third party dependencies podspecs for Kosara

  # Required by RNFirebase
  pod 'Firebase/Core'
  #pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  pod 'yoga', :path =>  '../node_modules/ReactCommon/yoga'

  # React Native
  pod 'React', :path => '../node_modules', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
    'RCTNetwork',
    'DevSupport'
  ]


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
```

### Error

```
ArgumentError - Malformed version number string ~> 5.0.1
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/version.rb:54:in `initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:154:in `name_and_version_from_string'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:214:in `block in generate_pod_names_and_versions'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:212:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:212:in `generate_pod_names_and_versions'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:240:in `pod_versions'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:87:in `version'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:168:in `block in dependencies_to_lock_pod_named'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:167:in `map'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:167:in `dependencies_to_lock_pod_named'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:296:in `block in detect_changes_with_podfile'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:294:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/lockfile.rb:294:in `detect_changes_with_podfile'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:233:in `block in generate_podfile_state'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:232:in `generate_podfile_state'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:82:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+~%3E+5.0.1&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Malformed version number string
   https://github.com/CocoaPods/CocoaPods/issues/7765 [closed] [44 comments]
   8 minutes ago

 - iOS framework addition failed due to a Cocoapods installation failure.
   https://github.com/CocoaPods/CocoaPods/issues/7767 [closed] [1 comment]
   22 May 2018

 - Malformed version number string Base.lproj
   https://github.com/CocoaPods/CocoaPods/issues/1582 [closed] [1 comment]
   12 Nov 2013

and 1 more at:
https://github.com/cocoapods/cocoapods/search?q=Malformed%20version%20number%20string%20~%3E%205.0.1&type=Issues&utf8=✓
Taruns-MacBook-Air:ios tarunnarula$

**Comment by ConfusedVorlon** [comment]
just noting that my bug report (malformed version number string) was closed as a duplicate of this.
https://github.com/CocoaPods/CocoaPods/issues/8240

fwiw - it seems like a fairly simple bug to me if cocoapods fails on gem 2.7.7 without saying why.

just checking the gem number and saying 'we can't run here' would have saved a bunch of time

**Comment by luckysunle** [comment]
if you account was managered,fix it with gem update --system 2.3.0 -n /usr/local/bin

**Comment by XiaBaKe** [comment]
podfile add

inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'  # 官方库
