### ISSUE TITLE
Xcode10 beta can't load bundles from CocoaPods

### ISSUE THREAD

**Issue by hengyizhangcn** [CocoaPods/CocoaPods#7823]
There are some libraries imported by Cocoapods. Like SVProgressHUD, etc.

When using Xcode10 beta to build the project, it's confirmed that the bundles imported by CocoaPods can't loaded to the app bundle.
Neither the simulator nor the true device, it happes every time.

But when using the Xcode version before 10, like 9.x, the problem is gone!
(Tips: pod version 1.3.1)

**Comment by dnkoutso** [comment]
Hello! Thanks for the report, is it possible to upload a sample app with this issue?

**Comment by dnkoutso** [comment]
It helps us a lot diagnose and debug quicker but I can try to create my own sample.

**Comment by hengyizhangcn** [comment]
@dnkoutso ，there is a demo
https://github.com/hengyizhangcn/CocoaPodsIssuesDemo.git

**Comment by dnkoutso** [comment]
excellent thanks!

**Comment by allenhumphreys** [comment]
Also had this issue, seems to be a problem with the new build system, not necessarily Xcode 10. The new build system is simply skipping the `[CP] Copy Pods Resources` script because it specifies an output folder (_${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}_) which is already created by some other task.

In the build log, you can see this warning:
<img width="982" alt="screen shot 2018-06-14 at 11 15 45 am" src="https://user-images.githubusercontent.com/8225090/41424848-cd4c1cb0-6fc4-11e8-81ff-096df8b55245.png">

And if you filter down on "Run" you'll see the script is not invoked. 
<img width="386" alt="screen shot 2018-06-14 at 11 19 55 am" src="https://user-images.githubusercontent.com/8225090/41424900-e48c3f4a-6fc4-11e8-880b-47328236b30a.png">

Work arounds
Removing the "Output Files" entry manually fixes the issue. Overriding the default usage of the new build system will also fix the issue.

**Comment by dnkoutso** [comment]
@allenhumphreys what version of CocoaPods are you using?

**Comment by allenhumphreys** [comment]
1.3.1

**Comment by dnkoutso** [comment]
@allenhumphreys this is fixed in >= 1.4.0 with https://github.com/CocoaPods/CocoaPods/pull/7209

I am inclined to resolve the issue but for now will keep it open and wait for sample or input from the original author.

**Comment by dnkoutso** [comment]
I am blind. There *is* a sample :)

**Comment by dnkoutso** [comment]
@hengyizhangcn what version of CocoaPods were you using?

**Comment by allenhumphreys** [comment]
@dnkoutso I upgraded to 1.5.3 and I'm still seeing this issue.

**Comment by dnkoutso** [comment]
If you remove the copy resources phase and `pod install` again do the input/output paths still include `${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH})`?

**Comment by allenhumphreys** [comment]
@dnkoutso My bad, it's actually working fine!

**Comment by dnkoutso** [comment]
I guess is the problem that `${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}` is present as a root folder or just any other resource already copied? If its the latter then this is a problem.

**Comment by dnkoutso** [comment]
ah ok! :D

**Comment by hengyizhangcn** [comment]
@dnkoutso , the CocoaPods' version is 1.5.3

**Comment by dnkoutso** [comment]
thanks, I think we slightly derailed here on the issue your original might still be a problem but I havent yet checked. Need Xcode 10 beta to be installed.

**Comment by dnkoutso** [comment]
@hengyizhangcn I could not reproduce.

The bundle is copied and it loads properly in the debugger. I do not see anything in the sample app, should I?

<img width="882" alt="screen_shot_2018-06-14_at_10_34_55_pm" src="https://user-images.githubusercontent.com/310370/41451723-391b3382-7023-11e8-8209-4545e017121e.png">

**Comment by hengyizhangcn** [comment]
It's approved that the project which created by CocoaPods version 1.3.1 or before can't run on Xcode10 beta. 
According to dnkoutso's advice, update to the newest CocoaPods, remove _Copy Pods Resources_ in the _Build Phases_ and _pod install_ again, the problem is gone! Simply, don't do any remove operation, just _pod install_ again after upgrade CocoaPods, the result is the same.
If the project is newly created by CocoaPods version 1.5.3(1.4.0 or later), it's unnecessary to worry about this issue described in #7823.
Many thanks to @dnkoutso @allenhumphreys !

**Comment by dnkoutso** [comment]
great! thanks for posting this for the next person who might hit this problem.

**Comment by hengyizhangcn** [comment]
This issue just tells us, it is very important to keep pace with the CocoaPods version release!

**Comment by wolffan** [comment]
I can reproduce this problem with Cocoapods version 1.3.5

The solution provided here (deleting the Copy won't work, assuming Copy is now Embed) doesn't work.

I've tried also moving to old build system and won't work either
